//! Shared model storage: scanning a root and generating
//! `extra_model_paths.yaml`.
//!
//! The mechanism is a regular part of ComfyUI; our job is to generate a
//! correct file and hand it to the instance. Only what affects the code is
//! written down here.
//!
//! **Sections are built from the subfolders that actually exist in the root,
//! not from a hardcoded list of keys.** The list of categories in ComfyUI is
//! assembled at runtime and grows from version to version
//! (`folder_paths.py:24-70`), so a baked-in list would go stale with the next
//! update. The known table below is needed for exactly two things: highlighting
//! the unrecognised in the interface, and offering to create the missing
//! standard folders.

use std::collections::BTreeMap;
use std::path::{Path, PathBuf};

use serde::{Deserialize, Serialize};

use crate::error::AppError;

/// The marker of a file of ours. ASCII and unchanged between versions: it is
/// what decides whether `extra_model_paths.yaml` in the user's folder may be
/// overwritten silently. Recognition must not be tied to human text — that
/// gets translated and edited, and the marker has to survive both.
pub const MARKER: &str = "# cpo:generated";

/// The header of the generated file.
///
/// In English deliberately: the file lives inside someone else's ComfyUI
/// installation and will be seen in issues and in other people's guides. It is
/// not an interface string, and `t()` has nothing to do with it.
const HEADER: &str = "# cpo:generated\n\
     # Generated by ComfyUI Portable Organizer. Manual edits will be overwritten.\n";

/// The categories known to us as of ComfyUI 0.30.
///
/// The list is taken from a real build, not invented. It does **not** limit
/// generation: any subfolder of the root becomes a key. It exists to tell "the
/// user created a new category" apart from "the user made a typo in `loras`",
/// and to offer creating what is missing.
const KNOWN: [&str; 26] = [
    "audio_encoders",
    "background_removal",
    "checkpoints",
    "clip",
    "clip_vision",
    "configs",
    "controlnet",
    "detection",
    "diffusers",
    "diffusion_models",
    "embeddings",
    "frame_interpolation",
    "geometry_estimation",
    "gligen",
    "hypernetworks",
    "latent_upscale_models",
    "loras",
    "model_patches",
    "optical_flow",
    "photomaker",
    "style_models",
    "text_encoders",
    "unet",
    "upscale_models",
    "vae",
    "vae_approx",
];

/// What is offered for creation in the shared root.
///
/// The whole known set except the legacy names: a shared folder mirroring
/// ComfyUI's model tree is exactly what the user expects. Eight of them used
/// to be offered, on the reasoning "no need to create anything extra", and it
/// looked as if the app were failing to create all the folders that matter.
///
/// The legacy `unet` and `clip` are excluded: the canonical
/// `diffusion_models` and `text_encoders` cover them, and creating both pairs
/// means creating confusion.
fn suggested() -> Vec<&'static str> {
    KNOWN
        .iter()
        .copied()
        .filter(|name| !LEGACY.iter().any(|(legacy, _)| legacy == name))
        .collect()
}

/// Legacy folder names. `folder_paths.py:111-114` reduces them to the
/// canonical ones, so we hand such a folder over under the canonical key too.
/// If both lie in the root, both paths go into one key as a multi-line block.
const LEGACY: [(&str, &str); 2] = [("unet", "diffusion_models"), ("clip", "text_encoders")];

/// The key is valid for this YAML and present in the example shipped with
/// ComfyUI — that is, a user creating such a folder is not being malicious,
/// they copied the sample. Sharing custom nodes cancels the reason this
/// project exists: instances are kept apart precisely because nodes conflict
/// with each other. Excluded unconditionally and silently in the YAML, with an
/// explanation in the interface.
const BLACKLIST: [&str; 1] = ["custom_nodes"];

#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize, specta::Type)]
#[serde(rename_all = "camelCase")]
pub enum CategoryStatus {
    /// The name matched a known category or a legacy variant of one.
    Recognized,
    /// The name is unknown. It still goes into the YAML: ComfyUI's list of
    /// categories keeps growing, and discarding the unfamiliar would mean
    /// breaking support for new versions in the name of tidiness. It is marked
    /// in the interface so that a typo like `lora` instead of `loras` catches
    /// the eye.
    Unknown,
    /// Blacklisted. Never goes into the YAML.
    Blocked,
}

#[derive(Debug, Clone, Serialize, Deserialize, specta::Type)]
#[serde(rename_all = "camelCase")]
pub struct SharedCategory {
    /// The subfolder's name exactly as it is on disk.
    pub folder: String,
    /// The key the folder will go into the YAML under. For legacy names it
    /// differs from `folder`; for blocked ones it is `None`.
    pub key: Option<String>,
    pub status: CategoryStatus,
    pub files: u32,
    /// `f64` rather than `u64`: specta forbids exporting integers that do not
    /// fit into a JavaScript number without losing precision.
    pub size_bytes: f64,
}

#[derive(Debug, Clone, Serialize, Deserialize, specta::Type)]
#[serde(rename_all = "camelCase")]
pub struct RootScan {
    pub path: String,
    /// The folder is absent or unavailable. Not an error: the root can be set
    /// ahead of time, and an external drive can be unplugged.
    pub available: bool,
    pub categories: Vec<SharedCategory>,
    /// Standard categories missing from the root. Offered for creation.
    pub missing: Vec<String>,
    pub total_files: u32,
    pub total_bytes: f64,
}

/// A single shared root in the settings.
#[derive(Debug, Clone, Serialize, Deserialize, specta::Type)]
#[serde(rename_all = "camelCase")]
pub struct SharedRoot {
    pub id: String,
    pub path: String,
    pub label: String,
    pub enabled: bool,
}

#[derive(Debug, Clone, Serialize, Deserialize, specta::Type)]
#[serde(rename_all = "camelCase")]
pub struct SharedSettings {
    /// Only one can be created in the interface so far, but the format is laid
    /// down as an array: the "fast SSD for checkpoints, HDD for the archive"
    /// scenario will fit without a migration — YAML can do it, one section per
    /// root, and the order of roots sets the search priority.
    pub roots: Vec<SharedRoot>,
    /// Goes into `is_default`. It only governs where ComfyUI puts newly
    /// downloaded files: the paths are additive either way.
    pub make_default_target: bool,
}

impl Default for SharedSettings {
    fn default() -> Self {
        // Downloaded once, available to all: that is what this section exists
        // for.
        Self { roots: Vec::new(), make_default_target: true }
    }
}

/// How the config is delivered to an instance.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize, specta::Type)]
#[serde(rename_all = "camelCase")]
pub enum ApplyMode {
    /// The file lives with us and is passed to the instance as an argument.
    /// Nothing is written into the user's folder. The default.
    Flag,
    /// The file is written to `<instance>/ComfyUI/extra_model_paths.yaml`.
    /// Needed by those who sometimes start the build from the `.bat`, past the
    /// app.
    InstanceFile,
}

#[derive(Debug, Clone, Copy, Serialize, Deserialize, specta::Type)]
#[serde(rename_all = "camelCase")]
pub struct InstanceShared {
    pub enabled: bool,
    pub apply_mode: ApplyMode,
}

impl Default for InstanceShared {
    fn default() -> Self {
        Self { enabled: false, apply_mode: ApplyMode::Flag }
    }
}

/// Reduces a subfolder's name to the canonical key if it is a legacy one.
fn canonical(folder: &str) -> &str {
    LEGACY
        .iter()
        .find(|(legacy, _)| *legacy == folder)
        .map_or(folder, |(_, target)| *target)
}

/// Reads the root's subfolders and counts files and size for each.
///
/// Recursively: models are often laid out in subfolders inside a category
/// (`checkpoints/sdxl/…`), and counting only the top level would mean showing
/// the user a zero where hundreds of gigabytes lie.
///
/// Read errors on individual entries are swallowed: an unreachable file inside
/// the shared folder is no reason to refuse generating the config.
pub fn scan_root(path: &Path) -> RootScan {
    let path = &normalize(path);
    let display = path.display().to_string();

    if !path.is_dir() {
        return RootScan {
            path: display,
            available: false,
            categories: Vec::new(),
            missing: suggested().into_iter().map(String::from).collect(),
            total_files: 0,
            total_bytes: 0.0,
        };
    }

    let mut categories = Vec::new();
    let mut present = Vec::new();

    let entries = match std::fs::read_dir(path) {
        Ok(entries) => entries,
        // The folder exists but will not be read — permissions or a lock. For
        // the interface that is the same as its absence: there is nothing to
        // show.
        Err(_) => {
            return RootScan {
                path: display,
                available: false,
                categories: Vec::new(),
                missing: suggested().into_iter().map(String::from).collect(),
                total_files: 0,
                total_bytes: 0.0,
            }
        }
    };

    for entry in entries.flatten() {
        // A file in the root is not a category. Skipped silently: a README
        // next to model folders is a common thing.
        if !entry.file_type().map(|t| t.is_dir()).unwrap_or(false) {
            continue;
        }
        let folder = entry.file_name().to_string_lossy().to_string();
        present.push(folder.clone());

        let blocked = BLACKLIST.contains(&folder.as_str());
        let key = (!blocked).then(|| canonical(&folder).to_string());
        let status = if blocked {
            CategoryStatus::Blocked
        } else if KNOWN.contains(&folder.as_str()) {
            CategoryStatus::Recognized
        } else {
            CategoryStatus::Unknown
        };

        let (files, size_bytes) = measure(&entry.path());

        categories.push(SharedCategory { folder, key, status, files, size_bytes });
    }

    // The order is fixed: recognised, then unrecognised, then excluded; by
    // name within a group. Otherwise the list would jump around between scans
    // — `read_dir` promises no order.
    categories.sort_by(|a, b| {
        let rank = |s: CategoryStatus| match s {
            CategoryStatus::Recognized => 0,
            CategoryStatus::Unknown => 1,
            CategoryStatus::Blocked => 2,
        };
        rank(a.status).cmp(&rank(b.status)).then(a.folder.cmp(&b.folder))
    });

    let missing = suggested()
        .into_iter()
        .filter(|s| !present.iter().any(|p| p == *s))
        // A legacy folder covers the need for the canonical one: if `unet/`
        // is there, offering to create `diffusion_models/` is pointless.
        .filter(|s| {
            !LEGACY
                .iter()
                .any(|(legacy, target)| target == s && present.iter().any(|p| p == legacy))
        })
        .map(|s| s.to_string())
        .collect();

    let total_files = categories
        .iter()
        .filter(|c| c.status != CategoryStatus::Blocked)
        .map(|c| c.files)
        .sum();
    let total_bytes = categories
        .iter()
        .filter(|c| c.status != CategoryStatus::Blocked)
        .map(|c| c.size_bytes)
        .sum();

    RootScan { path: display, available: true, categories, missing, total_files, total_bytes }
}

/// Counts files and bytes in a tree. Metadata only, the contents are not read.
fn measure(dir: &Path) -> (u32, f64) {
    let mut files = 0u32;
    let mut bytes = 0f64;
    let mut stack = vec![dir.to_path_buf()];

    while let Some(current) = stack.pop() {
        let Ok(entries) = std::fs::read_dir(&current) else {
            continue;
        };
        for entry in entries.flatten() {
            let Ok(kind) = entry.file_type() else { continue };
            if kind.is_dir() {
                stack.push(entry.path());
            } else if let Ok(meta) = entry.metadata() {
                files = files.saturating_add(1);
                bytes += meta.len() as f64;
            }
        }
    }

    (files, bytes)
}

/// Assembles the YAML for a set of roots.
///
/// Forward slashes: on Windows they work and need no escaping, while
/// backslashes would have to be doubled in YAML.
pub fn render_yaml(roots: &[(&RootScan, &str)], make_default: bool) -> String {
    let mut out = String::from(HEADER);

    for (index, (scan, _)) in roots.iter().enumerate() {
        // A section name of our own: the top-level key is arbitrary, the file
        // is simply iterated over by keys (`utils/extra_config.py:10`). Our
        // own name guarantees we will not collide with someone else's section.
        out.push_str(&format!("\ncpo_shared_{index}:\n"));
        out.push_str(&format!("  base_path: {}\n", slashes(&scan.path)));
        out.push_str(&format!("  is_default: {make_default}\n"));

        // Several folders may collapse into one key: `unet/` and
        // `diffusion_models/` both go into `diffusion_models`.
        let mut merged: BTreeMap<&str, Vec<&str>> = BTreeMap::new();
        for category in &scan.categories {
            let Some(key) = category.key.as_deref() else { continue };
            merged.entry(key).or_default().push(&category.folder);
        }

        for (key, mut folders) in merged {
            // The order within a key decides where ComfyUI puts newly
            // downloaded files: the target is `paths[0]`. Of two folders
            // merged into one key, the target has to be the canonical one, not
            // the legacy one.
            //
            // But the insertion depends on `is_default`, and depends the other
            // way round (`folder_paths.py:379-385`): with `false` the path is
            // appended at the end and the order is preserved, with `true` it
            // is inserted at the front, i.e. the order is reversed. Verified on
            // a real build: `diffusion_models/`, `unet/` arrived as
            // `[unet, diffusion_models]`.
            //
            // So with `is_default` the canonical one is written last — after
            // the reversal it ends up first.
            folders.sort_by_key(|folder| ((*folder == key) == make_default, *folder));
            if folders.len() == 1 {
                out.push_str(&format!("  {key}: {}/\n", folders[0]));
            } else {
                // The value is split on `\n` (`utils/extra_config.py:24`), so
                // several paths per key means a multi-line block.
                out.push_str(&format!("  {key}: |\n"));
                for folder in folders {
                    out.push_str(&format!("    {folder}/\n"));
                }
            }
        }
    }

    out
}

/// Backslashes into forward ones. YAML accepts both, but backslashes would
/// have to be escaped, and a forgotten escape breaks the config silently.
fn slashes(path: &str) -> String {
    path.replace('\\', "/")
}

/// Collapses `.` and `..` in the middle of a path.
///
/// `base_path` has to be absolute and readable: it lands in another
/// application's config and in the interface. `canonicalize` would return a
/// verbatim path with `\\?\`, which must not be shown to the user, and
/// `Path::join` does not remove `..` by itself. The same trick as in
/// `profiles::normalize` — what stands in the way of extracting it into a
/// shared place is precisely that only a dozen lines are duplicated here, and
/// coupling two modules for their sake costs more.
fn normalize(path: &Path) -> PathBuf {
    let mut parts: Vec<std::ffi::OsString> = Vec::new();
    for part in path.components() {
        use std::path::Component;
        match part {
            Component::CurDir => {}
            Component::ParentDir => {
                parts.pop();
            }
            other => parts.push(other.as_os_str().to_os_string()),
        }
    }
    parts.iter().fold(PathBuf::new(), |acc, p| acc.join(p))
}

/// Was this file written by us?
///
/// The marker is checked within the first few lines. Someone else's file
/// accidentally starting with our line is hard to imagine; mistaking theirs
/// for ours, on the other hand, means wiping out a working setting of the
/// user's.
pub fn is_ours(content: &str) -> bool {
    content.lines().take(5).any(|line| line.trim() == MARKER)
}

/// The path to `extra_model_paths.yaml` inside an instance.
///
/// `main.py:130-136` loads it from ComfyUI's own folder, not from the root of
/// the portable build — that is, one level deeper than where the `.bat` files
/// are.
pub fn instance_config_path(root: &Path) -> PathBuf {
    root.join("ComfyUI").join("extra_model_paths.yaml")
}

/// The backup name for someone else's file.
pub fn backup_path(config: &Path, stamp: u64) -> PathBuf {
    let mut name = config.file_name().unwrap_or_default().to_os_string();
    name.push(format!(".bak-{stamp}"));
    config.with_file_name(name)
}

/// Writes the YAML to the given path, creating the missing folders.
pub fn write_config(path: &Path, yaml: &str) -> Result<(), AppError> {
    if let Some(parent) = path.parent() {
        std::fs::create_dir_all(parent)
            .map_err(|e| AppError::because("shared.writeFailed", e))?;
    }
    std::fs::write(path, yaml).map_err(|e| AppError::because("shared.writeFailed", e))
}

/// The name of our config in the app data folder — for "flag" mode.
///
/// One file for all instances: the setting is shared, and keeping a copy per
/// instance would mean drifting apart at the first edit of the root.
pub fn flag_config_path(app_data_dir: &Path) -> PathBuf {
    app_data_dir.join("shared-models.yaml")
}

/// What came out of assembling the config from the settings.
pub struct Rendered {
    pub yaml: String,
    /// Roots that are not in place right now. An empty list means everything
    /// is available. The check has to happen **before** launch: otherwise the
    /// user learns about the unplugged external drive from a "model not found"
    /// error in the middle of their work.
    pub unavailable: Vec<String>,
    /// Not a single enabled root — there is nothing to generate.
    pub empty: bool,
}

/// Scans the enabled roots and assembles the YAML from them.
pub fn render_settings(settings: &SharedSettings) -> Rendered {
    let scans: Vec<RootScan> = settings
        .roots
        .iter()
        .filter(|r| r.enabled)
        .map(|r| scan_root(Path::new(&r.path)))
        .collect();

    let unavailable =
        scans.iter().filter(|s| !s.available).map(|s| s.path.clone()).collect::<Vec<_>>();

    // An unavailable root is not written into the config: ComfyUI does not
    // complain about a non-existent path, it just adds it silently, and there
    // would be nothing left to diagnose afterwards.
    let usable: Vec<(&RootScan, &str)> =
        scans.iter().filter(|s| s.available).map(|s| (s, "")).collect();

    Rendered {
        empty: usable.is_empty(),
        yaml: render_yaml(&usable, settings.make_default_target),
        unavailable,
    }
}

/// What is sitting in an instance's `extra_model_paths.yaml`.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize, specta::Type)]
#[serde(rename_all = "camelCase")]
pub enum InstanceFileState {
    /// There is no file — we write without asking.
    Absent,
    /// Ours, recognised by the marker — we update silently.
    Ours,
    /// Someone else's. Not touched until the user decides.
    Foreign,
    /// The file exists but will not be read. We do not touch it and we say so:
    /// overwriting what we failed to read is a sure way to destroy a working
    /// setting.
    Unreadable,
}

#[derive(Debug, Clone, Serialize, Deserialize, specta::Type)]
#[serde(rename_all = "camelCase")]
pub struct InstanceFileInfo {
    pub path: String,
    pub state: InstanceFileState,
    /// The contents of someone else's file — so the user can be shown exactly
    /// what they are about to replace. Empty for our own and for an absent
    /// one.
    pub content: Option<String>,
}

pub fn inspect_instance_file(root: &Path) -> InstanceFileInfo {
    let path = instance_config_path(root);
    let display = path.display().to_string();

    if !path.exists() {
        return InstanceFileInfo { path: display, state: InstanceFileState::Absent, content: None };
    }

    match std::fs::read_to_string(&path) {
        Ok(content) if is_ours(&content) => {
            InstanceFileInfo { path: display, state: InstanceFileState::Ours, content: None }
        }
        Ok(content) => InstanceFileInfo {
            path: display,
            state: InstanceFileState::Foreign,
            content: Some(content),
        },
        Err(_) => {
            InstanceFileInfo { path: display, state: InstanceFileState::Unreadable, content: None }
        }
    }
}

/// Puts our config into the instance's folder, preserving someone else's.
///
/// Returns the backup path if one was needed. Someone else's file is never
/// overwritten without a copy — not even when the user confirmed: the
/// confirmation is about replacement, not about destruction.
pub fn write_instance_file(root: &Path, yaml: &str, stamp: u64) -> Result<Option<String>, AppError> {
    let path = instance_config_path(root);
    let info = inspect_instance_file(root);

    let backup = match info.state {
        InstanceFileState::Unreadable => {
            return Err(AppError::with("shared.fileUnreadable", "path", path.display()))
        }
        InstanceFileState::Foreign => {
            let backup = backup_path(&path, stamp);
            std::fs::copy(&path, &backup)
                .map_err(|e| AppError::because("shared.backupFailed", e))?;
            Some(backup.display().to_string())
        }
        InstanceFileState::Absent | InstanceFileState::Ours => None,
    };

    write_config(&path, yaml)?;
    Ok(backup)
}

/// Removes our config from the instance's folder and puts someone else's back.
///
/// Someone else's file is not deleted under any circumstances: if what lies
/// there is not ours, it was put there after us, and it takes precedence.
pub fn remove_instance_file(root: &Path) -> Result<(), AppError> {
    let path = instance_config_path(root);
    let info = inspect_instance_file(root);

    if info.state != InstanceFileState::Ours {
        return Ok(());
    }

    std::fs::remove_file(&path).map_err(|e| AppError::because("shared.removeFailed", e))?;

    // The freshest copy is the one restored.
    if let Some(backup) = latest_backup(&path) {
        std::fs::rename(&backup, &path)
            .map_err(|e| AppError::because("shared.restoreFailed", e))?;
    }
    Ok(())
}

/// The freshest backup next to the config.
///
/// The stamp is compared **as a number**, not as a string. Lexicographically
/// `.bak-5` is greater than `.bak-40`, and the older copy would be the one
/// restored. On real epoch stamps this would not surface until the year 2286
/// — all of them are ten digits long — meaning the defect would have reached
/// production unnoticed.
fn latest_backup(config: &Path) -> Option<PathBuf> {
    let dir = config.parent()?;
    let prefix = format!("{}.bak-", config.file_name()?.to_string_lossy());

    std::fs::read_dir(dir)
        .ok()?
        .flatten()
        .map(|e| e.file_name().to_string_lossy().to_string())
        .filter_map(|name| {
            let stamp = name.strip_prefix(&prefix)?.parse::<u64>().ok()?;
            Some((stamp, name))
        })
        .max_by_key(|(stamp, _)| *stamp)
        .map(|(_, name)| dir.join(name))
}
