//! Общее хранилище моделей: сканирование корня и генерация `extra_model_paths.yaml`.
//!
//! Механизм в ComfyUI штатный, наша задача — сгенерировать корректный файл
//! и подсунуть его инстансу. Находки из исходников, определившие дизайн,
//! собраны в `plan/shared-models.md`; здесь только то, что влияет на код.
//!
//! **Секции строятся из реально существующих подпапок корня, а не из
//! захардкоженного списка ключей.** Список категорий в ComfyUI собирается
//! в рантайме и растёт от версии к версии (`folder_paths.py:24-70`), так что
//! зашитый перечень протух бы с ближайшим обновлением. Известная таблица
//! ниже нужна ровно для двух вещей: подсветить нераспознанное в интерфейсе
//! и предложить создать недостающие стандартные папки.

use std::collections::BTreeMap;
use std::path::{Path, PathBuf};

use serde::{Deserialize, Serialize};

use crate::error::AppError;

/// Маркер своего файла. ASCII и неизменен между версиями: по нему решается,
/// можно ли перезаписать `extra_model_paths.yaml` в папке пользователя молча.
/// Привязывать распознавание к человеческому тексту нельзя — он переводится
/// и правится, а маркер обязан пережить и то и другое.
pub const MARKER: &str = "# cpo:generated";

/// Шапка сгенерированного файла.
///
/// По-английски намеренно: файл живёт внутри чужой установки ComfyUI,
/// его увидят в issue и в чужой инструкции. Это не строка интерфейса,
/// и `t()` к ней отношения не имеет.
const HEADER: &str = "# cpo:generated\n\
     # Generated by ComfyUI Portable Organizer. Manual edits will be overwritten.\n";

/// Категории, известные нам на момент ComfyUI 0.30.
///
/// Список снят с реальной сборки, а не выдуман. Он **не** ограничивает
/// генерацию: любая подпапка корня становится ключом. Нужен, чтобы отличить
/// «пользователь завёл новую категорию» от «пользователь опечатался
/// в `loras`» и предложить создать недостающее.
const KNOWN: [&str; 26] = [
    "audio_encoders",
    "background_removal",
    "checkpoints",
    "clip",
    "clip_vision",
    "configs",
    "controlnet",
    "detection",
    "diffusers",
    "diffusion_models",
    "embeddings",
    "frame_interpolation",
    "geometry_estimation",
    "gligen",
    "hypernetworks",
    "latent_upscale_models",
    "loras",
    "model_patches",
    "optical_flow",
    "photomaker",
    "style_models",
    "text_encoders",
    "unet",
    "upscale_models",
    "vae",
    "vae_approx",
];

/// Что стоит предложить создать в пустом корне. Подмножество `KNOWN`:
/// звать пользователя заводить двадцать шесть папок, из которых он
/// воспользуется пятью, — вредный совет.
const SUGGESTED: [&str; 8] = [
    "checkpoints",
    "loras",
    "vae",
    "controlnet",
    "upscale_models",
    "embeddings",
    "text_encoders",
    "diffusion_models",
];

/// Устаревшие имена папок. `folder_paths.py:111-114` сводит их к каноническим,
/// поэтому и мы отдаём такую папку под каноническим ключом. Если в корне лежат
/// обе — обе пути уезжают в один ключ многострочным блоком.
const LEGACY: [(&str, &str); 2] = [("unet", "diffusion_models"), ("clip", "text_encoders")];

/// Ключ валиден для этого YAML и есть в примере, который поставляется
/// с ComfyUI, — то есть пользователь заведёт такую папку не по злому умыслу,
/// а скопировав образец. Шаринг кастомных нод отменяет причину существования
/// проекта: инстансы разведены ровно потому, что ноды конфликтуют между собой.
/// Исключается безусловно и молча в YAML, с объяснением в интерфейсе.
const BLACKLIST: [&str; 1] = ["custom_nodes"];

#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize, specta::Type)]
#[serde(rename_all = "camelCase")]
pub enum CategoryStatus {
    /// Имя совпало с известной категорией или с её устаревшим вариантом.
    Recognized,
    /// Имя неизвестно. В YAML всё равно попадает: список категорий ComfyUI
    /// растёт, и отбрасывать незнакомое значило бы ломать поддержку новых
    /// версий ради аккуратности. В интерфейсе помечается, чтобы опечатка
    /// вроде `lora` вместо `loras` бросалась в глаза.
    Unknown,
    /// Чёрный список. В YAML не попадает никогда.
    Blocked,
}

#[derive(Debug, Clone, Serialize, Deserialize, specta::Type)]
#[serde(rename_all = "camelCase")]
pub struct SharedCategory {
    /// Имя подпапки как оно есть на диске.
    pub folder: String,
    /// Ключ, под которым папка уедет в YAML. У устаревших имён отличается
    /// от `folder`; у заблокированных — `None`.
    pub key: Option<String>,
    pub status: CategoryStatus,
    pub files: u32,
    /// `f64`, а не `u64`: specta запрещает экспорт целых, не помещающихся
    /// в число JavaScript без потери точности.
    pub size_bytes: f64,
}

#[derive(Debug, Clone, Serialize, Deserialize, specta::Type)]
#[serde(rename_all = "camelCase")]
pub struct RootScan {
    pub path: String,
    /// Папки нет или она недоступна. Не ошибка: корень можно задать заранее,
    /// а внешний диск — отключить.
    pub available: bool,
    pub categories: Vec<SharedCategory>,
    /// Стандартные категории, которых в корне нет. Предлагаются к созданию.
    pub missing: Vec<String>,
    pub total_files: u32,
    pub total_bytes: f64,
}

/// Один общий корень в настройках.
#[derive(Debug, Clone, Serialize, Deserialize, specta::Type)]
#[serde(rename_all = "camelCase")]
pub struct SharedRoot {
    pub id: String,
    pub path: String,
    pub label: String,
    pub enabled: bool,
}

#[derive(Debug, Clone, Serialize, Deserialize, specta::Type)]
#[serde(rename_all = "camelCase")]
pub struct SharedSettings {
    /// В интерфейсе пока заводится один, но формат заложен массивом:
    /// сценарий «быстрый SSD под checkpoints, HDD под архив» ляжет
    /// без миграции — YAML это умеет, одна секция на корень, а порядок
    /// корней определяет приоритет поиска.
    pub roots: Vec<SharedRoot>,
    /// Уезжает в `is_default`. Управляет только тем, куда ComfyUI кладёт
    /// вновь скачанное: пути в любом случае аддитивны.
    pub make_default_target: bool,
}

impl Default for SharedSettings {
    fn default() -> Self {
        // Скачал один раз — доступно всем: ради этого раздел и заведён.
        Self { roots: Vec::new(), make_default_target: true }
    }
}

/// Способ доставки конфига инстансу.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize, specta::Type)]
#[serde(rename_all = "camelCase")]
pub enum ApplyMode {
    /// Файл живёт у нас, инстансу передаётся аргументом. В папку
    /// пользователя не пишется ничего. По умолчанию.
    Flag,
    /// Файл пишется в `<instance>/ComfyUI/extra_model_paths.yaml`. Нужен тем,
    /// кто иногда стартует сборку через `.bat` мимо приложения.
    InstanceFile,
}

#[derive(Debug, Clone, Copy, Serialize, Deserialize, specta::Type)]
#[serde(rename_all = "camelCase")]
pub struct InstanceShared {
    pub enabled: bool,
    pub apply_mode: ApplyMode,
}

impl Default for InstanceShared {
    fn default() -> Self {
        Self { enabled: false, apply_mode: ApplyMode::Flag }
    }
}

/// Приводит имя подпапки к каноническому ключу, если оно устаревшее.
fn canonical(folder: &str) -> &str {
    LEGACY
        .iter()
        .find(|(legacy, _)| *legacy == folder)
        .map_or(folder, |(_, target)| *target)
}

/// Читает подпапки корня и считает по каждой файлы и объём.
///
/// Рекурсивно: модели часто разложены по подпапкам внутри категории
/// (`checkpoints/sdxl/…`), и считать только верхний уровень значило бы
/// показать пользователю ноль там, где лежат сотни гигабайт.
///
/// Ошибки чтения отдельных элементов проглатываются: недоступный файл
/// внутри общей папки не повод отказать в генерации конфига.
pub fn scan_root(path: &Path) -> RootScan {
    let path = &normalize(path);
    let display = path.display().to_string();

    if !path.is_dir() {
        return RootScan {
            path: display,
            available: false,
            categories: Vec::new(),
            missing: SUGGESTED.iter().map(|s| s.to_string()).collect(),
            total_files: 0,
            total_bytes: 0.0,
        };
    }

    let mut categories = Vec::new();
    let mut present = Vec::new();

    let entries = match std::fs::read_dir(path) {
        Ok(entries) => entries,
        // Папка есть, но не читается — правами или занятостью. Для интерфейса
        // это то же самое, что её нет: показать нечего.
        Err(_) => {
            return RootScan {
                path: display,
                available: false,
                categories: Vec::new(),
                missing: SUGGESTED.iter().map(|s| s.to_string()).collect(),
                total_files: 0,
                total_bytes: 0.0,
            }
        }
    };

    for entry in entries.flatten() {
        // Файл в корне — не категория. Пропускаем молча: README рядом
        // с папками моделей вещь обычная.
        if !entry.file_type().map(|t| t.is_dir()).unwrap_or(false) {
            continue;
        }
        let folder = entry.file_name().to_string_lossy().to_string();
        present.push(folder.clone());

        let blocked = BLACKLIST.contains(&folder.as_str());
        let key = (!blocked).then(|| canonical(&folder).to_string());
        let status = if blocked {
            CategoryStatus::Blocked
        } else if KNOWN.contains(&folder.as_str()) {
            CategoryStatus::Recognized
        } else {
            CategoryStatus::Unknown
        };

        let (files, size_bytes) = measure(&entry.path());

        categories.push(SharedCategory { folder, key, status, files, size_bytes });
    }

    // Порядок фиксированный: распознанные, потом нераспознанные, потом
    // исключённые; внутри группы по имени. Иначе список прыгал бы между
    // сканами — `read_dir` порядка не обещает.
    categories.sort_by(|a, b| {
        let rank = |s: CategoryStatus| match s {
            CategoryStatus::Recognized => 0,
            CategoryStatus::Unknown => 1,
            CategoryStatus::Blocked => 2,
        };
        rank(a.status).cmp(&rank(b.status)).then(a.folder.cmp(&b.folder))
    });

    let missing = SUGGESTED
        .iter()
        .filter(|s| !present.iter().any(|p| p == *s))
        // Устаревшая папка закрывает потребность канонической: если лежит
        // `unet/`, предлагать завести `diffusion_models/` незачем.
        .filter(|s| {
            !LEGACY
                .iter()
                .any(|(legacy, target)| target == *s && present.iter().any(|p| p == legacy))
        })
        .map(|s| s.to_string())
        .collect();

    let total_files = categories
        .iter()
        .filter(|c| c.status != CategoryStatus::Blocked)
        .map(|c| c.files)
        .sum();
    let total_bytes = categories
        .iter()
        .filter(|c| c.status != CategoryStatus::Blocked)
        .map(|c| c.size_bytes)
        .sum();

    RootScan { path: display, available: true, categories, missing, total_files, total_bytes }
}

/// Считает файлы и байты в дереве. Только метаданные, содержимое не читается.
fn measure(dir: &Path) -> (u32, f64) {
    let mut files = 0u32;
    let mut bytes = 0f64;
    let mut stack = vec![dir.to_path_buf()];

    while let Some(current) = stack.pop() {
        let Ok(entries) = std::fs::read_dir(&current) else {
            continue;
        };
        for entry in entries.flatten() {
            let Ok(kind) = entry.file_type() else { continue };
            if kind.is_dir() {
                stack.push(entry.path());
            } else if let Ok(meta) = entry.metadata() {
                files = files.saturating_add(1);
                bytes += meta.len() as f64;
            }
        }
    }

    (files, bytes)
}

/// Собирает YAML для набора корней.
///
/// Прямые слэши: на Windows они работают и не требуют экранирования,
/// а обратные в YAML пришлось бы удваивать.
pub fn render_yaml(roots: &[(&RootScan, &str)], make_default: bool) -> String {
    let mut out = String::from(HEADER);

    for (index, (scan, _)) in roots.iter().enumerate() {
        // Собственное имя секции: ключ верхнего уровня произвольен, файл
        // просто итерируется по ключам (`utils/extra_config.py:10`).
        // Своё имя гарантирует, что мы не столкнёмся с чужой секцией.
        out.push_str(&format!("\ncpo_shared_{index}:\n"));
        out.push_str(&format!("  base_path: {}\n", slashes(&scan.path)));
        out.push_str(&format!("  is_default: {make_default}\n"));

        // Несколько папок могут схлопнуться в один ключ: `unet/` и
        // `diffusion_models/` оба уезжают в `diffusion_models`.
        let mut merged: BTreeMap<&str, Vec<&str>> = BTreeMap::new();
        for category in &scan.categories {
            let Some(key) = category.key.as_deref() else { continue };
            merged.entry(key).or_default().push(&category.folder);
        }

        for (key, mut folders) in merged {
            // Каноническая папка первой, устаревшие следом: `add_model_folder_path`
            // складывает пути по порядку, и порядок определяет, где ComfyUI
            // ищет раньше. Без явной сортировки он вышел бы алфавитным,
            // то есть случайным — `clip/` опережал бы `text_encoders/`,
            // а `diffusion_models/` опережал бы `unet/`.
            folders.sort_by_key(|folder| (*folder != key, *folder));
            if folders.len() == 1 {
                out.push_str(&format!("  {key}: {}/\n", folders[0]));
            } else {
                // Значение режется по `\n` (`utils/extra_config.py:24`),
                // поэтому несколько путей на ключ — это многострочный блок.
                out.push_str(&format!("  {key}: |\n"));
                for folder in folders {
                    out.push_str(&format!("    {folder}/\n"));
                }
            }
        }
    }

    out
}

/// Обратные слэши на прямые. YAML принимает и те и другие, но обратные
/// пришлось бы экранировать, а забытое экранирование ломает конфиг молча.
fn slashes(path: &str) -> String {
    path.replace('\\', "/")
}

/// Схлопывает `.` и `..` в середине пути.
///
/// `base_path` обязан быть абсолютным и читаемым: он попадает в конфиг чужого
/// приложения и в интерфейс. `canonicalize` вернул бы verbatim-путь с `\\?\`,
/// который показывать пользователю нельзя, а `Path::join` сам `..` не убирает.
/// Тот же приём, что в `profiles::normalize`, — вынести в общее место мешает
/// ровно то, что дублируется здесь десяток строк, а связывать два модуля
/// ради них дороже.
fn normalize(path: &Path) -> PathBuf {
    let mut parts: Vec<std::ffi::OsString> = Vec::new();
    for part in path.components() {
        use std::path::Component;
        match part {
            Component::CurDir => {}
            Component::ParentDir => {
                parts.pop();
            }
            other => parts.push(other.as_os_str().to_os_string()),
        }
    }
    parts.iter().fold(PathBuf::new(), |acc, p| acc.join(p))
}

/// Файл написан нами?
///
/// Проверяется маркер в первых строках. Чужой файл, случайно начинающийся
/// с нашей строки, представить трудно; зато перепутать свой с чужим —
/// значит затереть работающую настройку пользователя.
pub fn is_ours(content: &str) -> bool {
    content.lines().take(5).any(|line| line.trim() == MARKER)
}

/// Путь к `extra_model_paths.yaml` внутри инстанса.
///
/// `main.py:130-136` грузит его из папки самого ComfyUI, а не из корня
/// портабл-сборки — то есть на уровень глубже, чем лежат `.bat`.
pub fn instance_config_path(root: &Path) -> PathBuf {
    root.join("ComfyUI").join("extra_model_paths.yaml")
}

/// Имя резервной копии чужого файла.
pub fn backup_path(config: &Path, stamp: u64) -> PathBuf {
    let mut name = config.file_name().unwrap_or_default().to_os_string();
    name.push(format!(".bak-{stamp}"));
    config.with_file_name(name)
}

/// Пишет YAML по указанному пути, создавая недостающие папки.
pub fn write_config(path: &Path, yaml: &str) -> Result<(), AppError> {
    if let Some(parent) = path.parent() {
        std::fs::create_dir_all(parent)
            .map_err(|e| AppError::because("shared.writeFailed", e))?;
    }
    std::fs::write(path, yaml).map_err(|e| AppError::because("shared.writeFailed", e))
}
