//! Extracting the graph from a PNG generated by ComfyUI.
//!
//! Checked against a real image from the `output` folder rather than a
//! hand-assembled one: the chunk is put there by ComfyUI itself, and an
//! invented sample would only prove that we can read our own invention.
//!
//! Run: cargo run --example check_png [path-to-png]

use std::path::PathBuf;

use cpo_desktop_lib::workflows;

/// The `output` folder of a working build. Overridden by the argument.
const DEFAULT: &str =
    r"d:\program_files\comfyui\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\ComfyUI\output";

fn main() {
    let mut failures = 0;

    // --- a real image -------------------------------------------------------
    match real_png() {
        Some(path) => {
            println!("[CHECK] image: {}", path.display());
            let bytes = std::fs::read(&path).expect("does not read");
            let graph = workflows::workflow_from_png(&bytes);
            failures += check("the graph is found in the tEXt chunk", graph.is_some(), String::new());

            if let Some(graph) = graph {
                let types = workflows::node_types(&graph);
                failures += check(
                    "what was found parses as a workflow",
                    types.is_some(),
                    String::new(),
                );
                if let Some(types) = types {
                    println!("       node classes: {}", types.len());
                    failures += check("there are nodes in the graph", !types.is_empty(), String::new());
                }
            }
        }
        None => {
            println!("[CHECK] no real image was found — this part is skipped");
            println!("        path: {DEFAULT}");
        }
    }

    // --- things that are not a graph ---------------------------------------
    let signature = [0x89u8, b'P', b'N', b'G', 0x0D, 0x0A, 0x1A, 0x0A];

    let mut bare = signature.to_vec();
    bare.extend_from_slice(&0u32.to_be_bytes());
    bare.extend_from_slice(b"IEND");
    bare.extend_from_slice(&[0, 0, 0, 0]);
    failures += check(
        "a PNG with no graph is a refusal, not an invention",
        workflows::workflow_from_png(&bare).is_none(),
        String::new(),
    );

    failures += check(
        "not a PNG at all is a refusal",
        workflows::workflow_from_png(b"{\"nodes\":[]}").is_none(),
        String::new(),
    );

    // A truncated file: the chunk's declared length is greater than the bytes
    // left. A naive parse here would run past the buffer and crash the app.
    let mut truncated = signature.to_vec();
    truncated.extend_from_slice(&999_999u32.to_be_bytes());
    truncated.extend_from_slice(b"tEXt");
    truncated.extend_from_slice(b"workflow\0{\"nodes\"");
    failures += check(
        "a truncated file does not crash the parse",
        workflows::workflow_from_png(&truncated).is_none(),
        String::new(),
    );

    // A chunk with a different key must not be taken: `prompt` is the API
    // format, and it does not open in the editor.
    let mut prompt_only = signature.to_vec();
    let payload = b"prompt\0{\"1\":{\"class_type\":\"KSampler\"}}";
    prompt_only.extend_from_slice(&(payload.len() as u32).to_be_bytes());
    prompt_only.extend_from_slice(b"tEXt");
    prompt_only.extend_from_slice(payload);
    prompt_only.extend_from_slice(&[0, 0, 0, 0]);
    prompt_only.extend_from_slice(&0u32.to_be_bytes());
    prompt_only.extend_from_slice(b"IEND");
    prompt_only.extend_from_slice(&[0, 0, 0, 0]);
    failures += check(
        "the prompt chunk is not passed off as a graph",
        workflows::workflow_from_png(&prompt_only).is_none(),
        String::new(),
    );

    println!("\nChecks failed: {failures}");
    if failures > 0 {
        std::process::exit(1);
    }
}

fn real_png() -> Option<PathBuf> {
    let dir = std::env::args().nth(1).unwrap_or_else(|| DEFAULT.to_string());
    let dir = PathBuf::from(dir);
    if dir.is_file() {
        return Some(dir);
    }
    let mut names: Vec<PathBuf> = std::fs::read_dir(&dir)
        .ok()?
        .flatten()
        .map(|e| e.path())
        .filter(|p| p.extension().map(|e| e.eq_ignore_ascii_case("png")).unwrap_or(false))
        .collect();
    names.sort();
    names.into_iter().next()
}

fn check(what: &str, ok: bool, detail: String) -> u32 {
    println!(
        "{} {what}{}",
        if ok { "  OK  " } else { " FAIL " },
        if detail.is_empty() { String::new() } else { format!(" — {detail}") }
    );
    u32::from(!ok)
}
