// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE } from "@tauri-apps/api/core";
import * as __TAURI_EVENT from "@tauri-apps/api/event";

/** Commands */
export const commands = {
	/**
	 *  The settings read at startup: theme, language, rail state, plus the system
	 *  locale and the paths for the "About" section.
	 */
	loadBootstrap: () => typedError<Bootstrap, AppError>(__TAURI_INVOKE("load_bootstrap")),
	saveSettings: (settings: UiSettings) => typedError<null, AppError>(__TAURI_INVOKE("save_settings", { settings })),
	listInstances: () => typedError<Instance[], AppError>(__TAURI_INVOKE("list_instances")),
	/**
	 *  Checks the chosen folder and suggests a name, a port and a colour along the
	 *  way.
	 * 
	 *  The check and the suggestions arrive in one response: the add screen shows
	 *  them together, and there is no point splitting that into three calls.
	 */
	probeFolder: (path: string) => typedError<ProbeResult, AppError>(__TAURI_INVOKE("probe_folder", { path })),
	suggestAccent: () => typedError<Accent, AppError>(__TAURI_INVOKE("suggest_accent")),
	addInstance: (path: string, edit: InstanceEdit) => typedError<Instance, AppError>(__TAURI_INVOKE("add_instance", { path, edit })),
	updateInstance: (id: string, edit: InstanceEdit) => typedError<Instance, AppError>(__TAURI_INVOKE("update_instance", { id, edit })),
	/**  Removes an instance from the registry. The folder on disk stays untouched. */
	removeInstance: (id: string) => typedError<null, AppError>(__TAURI_INVOKE("remove_instance", { id })),
	/**
	 *  Measures an instance's size on disk.
	 * 
	 *  The command is `async`, so it runs off the main thread and the interface
	 *  does not freeze for all the minutes of the walk. `None` means a measurement
	 *  is already running.
	 */
	measureInstanceSize: (id: string) => typedError<{
	id: string,
	bytes: number | null,
	measuredAt: number | null,
} | null, AppError>(__TAURI_INVOKE("measure_instance_size", { id })),
	probeArchive: (path: string) => typedError<ArchiveInfo, AppError>(__TAURI_INVOKE("probe_archive", { path })),
	checkTargets: (info: ArchiveInfo, targets: InstallTarget[]) => typedError<TargetCheck[], AppError>(__TAURI_INVOKE("check_targets", { info, targets })),
	archiveHistory: () => typedError<ArchiveRecord[], AppError>(__TAURI_INVOKE("archive_history")),
	forgetArchive: (path: string) => typedError<null, AppError>(__TAURI_INVOKE("forget_archive", { path })),
	/**
	 *  Unpacks the archive into the targets and registers them.
	 * 
	 *  The command is `async`, so the minutes of extraction do not block the main
	 *  thread. Progress goes as events: there is nothing to return it in, a
	 *  command answers once.
	 */
	runInstall: (info: ArchiveInfo, targets: InstallTarget[]) => typedError<Instance[], AppError>(__TAURI_INVOKE("run_install", { info, targets })),
	/**
	 *  Asks the wizard to stop. It is checked between files, so a cancelled
	 *  install leaves no half-unpacked tree behind.
	 */
	cancelInstall: () => typedError<null, AppError>(__TAURI_INVOKE("cancel_install")),
	/**  An instance's launch profiles, parsed from its `.bat` right now. */
	instanceProfiles: (id: string) => typedError<LaunchProfile[], AppError>(__TAURI_INVOKE("instance_profiles", { id })),
	/**
	 *  The final launch command — the one that will actually go to the system.
	 * 
	 *  Shown in the argument editor: `--port` and `--disable-auto-launch` are
	 *  added by us, and without a preview the user would be arguing with the
	 *  invisible.
	 */
	previewCommand: (id: string, profileId: string) => typedError<string[], AppError>(__TAURI_INVOKE("preview_command", { id, profileId })),
	/**  Saves a custom launch profile. */
	saveCustomProfile: (id: string, profile: CustomProfile) => typedError<Instance, AppError>(__TAURI_INVOKE("save_custom_profile", { id, profile })),
	removeCustomProfile: (id: string, profileId: string) => typedError<Instance, AppError>(__TAURI_INVOKE("remove_custom_profile", { id, profileId })),
	/**  This build's models and which of them are already in the shared folder. */
	scanInstanceModels: (id: string) => typedError<ModelsScan, AppError>(__TAURI_INVOKE("scan_instance_models", { id })),
	/**
	 *  Moves the selected models into the shared folder.
	 * 
	 *  The selection arrives as "category and model" pairs, the same as for the
	 *  cleanup: on screen the toggle sits next to every model, not next to a whole
	 *  category.
	 * 
	 *  Refuses for a running build: files must not be taken out from under a
	 *  running ComfyUI — it holds them open and already resolved the paths at
	 *  startup.
	 */
	migrateModels: (id: string, items: ([string, string])[]) => typedError<MigrateOutcome, AppError>(__TAURI_INVOKE("migrate_models", { id, items })),
	cancelMigrate: () => typedError<null, AppError>(__TAURI_INVOKE("cancel_migrate")),
	/**
	 *  Removes from a build what already lies in the shared folder.
	 * 
	 *  Three conditions are checked here and not only on the screen: the build is
	 *  stopped, it is connected to shared models, and every entry has been
	 *  recognised as a duplicate afresh inside `remove_duplicates`. Deletion is
	 *  not the place where input data can be trusted.
	 */
	removeDuplicateModels: (id: string, items: ([string, string])[]) => typedError<CleanupOutcome, AppError>(__TAURI_INVOKE("remove_duplicate_models", { id, items })),
	/**
	 *  Where to put a fresh library if the user did not choose themselves.
	 * 
	 *  Next to the shared models root — those usually lie on a spacious drive, and
	 *  keeping workflows in the same place is sensible. There is no hard link: the
	 *  library works without shared models, so if there are none we simply stay
	 *  silent.
	 */
	suggestLibraryPath: () => typedError<string | null, AppError>(__TAURI_INVOKE("suggest_library_path")),
	loadLibrarySettings: () => typedError<LibrarySettings, AppError>(__TAURI_INVOKE("load_library_settings")),
	saveLibrarySettings: (library: LibrarySettings) => typedError<null, AppError>(__TAURI_INVOKE("save_library_settings", { library })),
	/**
	 *  Reads the whole library.
	 * 
	 *  In a blocking thread: walking the tree over a couple of hundred workflows
	 *  means thousands of disk accesses plus parsing every JSON for the sake of
	 *  the node list.
	 */
	scanLibrary: (path: string) => typedError<LibraryScan, AppError>(__TAURI_INVOKE("scan_library", { path })),
	/**
	 *  Puts a file from disk into the library.
	 * 
	 *  Accepts both `.json` and `.png`: an image from the `output` folder carries
	 *  the graph with it, and "drag the picture in" is the most common way of
	 *  getting back to a successful generation. In both cases what lands in the
	 *  library is a `.json` — that is what will later travel to an instance.
	 * 
	 *  Not a workflow means a refusal with an explanation: the library has to stay
	 *  a library of workflows, not a dumping ground for JSON.
	 */
	addWorkflowFile: (library: string, source: string, rel: string | null, overwrite: boolean) => typedError<string, AppError>(__TAURI_INVOKE("add_workflow_file", { library, source, rel, overwrite })),
	/**
	 *  Puts a graph that arrived as text into the library.
	 * 
	 *  The same end of the road as for a file, only the source differs: workflows
	 *  are sent as text — in a chat, on a forum — more often than as files, and
	 *  saving what was sent into a file merely to pick it in a dialog right after
	 *  is a wasted lap.
	 * 
	 *  The name comes from an input field, so it is checked here rather than
	 *  trusted: it lands in a path. There is no overwriting here either — a taken
	 *  name is a refusal, not a replacement: replacing would mean erasing one
	 *  piece of work with another.
	 */
	addWorkflowText: (library: string, name: string, content: string) => typedError<string, AppError>(__TAURI_INVOKE("add_workflow_text", { library, name, content })),
	/**  Edits a manifest record: favourite, tags, note. */
	setWorkflowMeta: (library: string, rel: string, meta: WorkflowMeta) => typedError<null, AppError>(__TAURI_INVOKE("set_workflow_meta", { library, rel, meta })),
	/**
	 *  Removes a lost record from the manifest.
	 * 
	 *  The record only: this command does not touch files at all — it is called
	 *  precisely when the file is already gone.
	 */
	forgetWorkflow: (library: string, rel: string) => typedError<null, AppError>(__TAURI_INVOKE("forget_workflow", { library, rel })),
	/**
	 *  The workflows lying inside a build.
	 * 
	 *  For a running one we ask over the API, for a stopped one we read the
	 *  folder. The difference is not cosmetic: for a running one the answer
	 *  accounts for what it saved a minute ago, and for a stopped one there is no
	 *  other source anyway.
	 */
	instanceWorkflows: (id: string, library: string) => typedError<InstanceWorkflow[], AppError>(__TAURI_INVOKE("instance_workflows", { id, library })),
	/**
	 *  A build's workflow folder — for the "show in Explorer" button.
	 * 
	 *  Existence is checked here: a stopped build that has not saved anything yet
	 *  has no such folder at all, and there is nothing to call Explorer with.
	 */
	instanceWorkflowsDir: (id: string) => typedError<InstanceWorkflowsDir, AppError>(__TAURI_INVOKE("instance_workflows_dir", { id })),
	/**
	 *  Moves a workflow from a build into the library: none of it stays in the
	 *  build.
	 * 
	 *  The order here is the only protection against losing someone's work, and it
	 *  is the same as for moving models: write the copy, **read it back and
	 *  compare**, and only then remove the source. Until the copy is verified, the
	 *  original has to stay in hand.
	 * 
	 *  There is no overwriting at all. A taken name used to raise a "replace?"
	 *  question, and it was harmless while taking meant copying: whatever the
	 *  answer, the workflow stayed in the build. For a move the price of the
	 *  answer is different — "replace" would erase one piece of work with another,
	 *  leaving a copy of neither.
	 * 
	 *  Instead of replacing there is `target`: take it under a free name. A taken
	 *  name stopped being a dead end, yet diverged versions stay two different
	 *  files rather than one on top of the other.
	 * 
	 *  For a running build the source is removed by the build itself, through its
	 *  own API: the workflow folder belongs to it, and it knows nothing of edits
	 *  from outside.
	 */
	pullWorkflow: (id: string, rel: string, library: string, target: string | null) => typedError<string, AppError>(__TAURI_INVOKE("pull_workflow", { id, rel, library, target })),
	/**
	 *  Puts a workflow from the library into a build.
	 * 
	 *  For a running one it goes through the API with `overwrite=false`, and **a
	 *  409 comes back as a fork in the road**, not as an error: silently erasing
	 *  someone else's workflow is not allowed. For a stopped one it goes as a
	 *  file, with the same existence check.
	 */
	pushWorkflow: (id: string, library: string, rel: string, overwrite: boolean) => typedError<PushOutcome, AppError>(__TAURI_INVOKE("push_workflow", { id, library, rel, overwrite })),
	/**
	 *  A workflow's compatibility with every registered build.
	 * 
	 *  Computed for all of them at once: the user is choosing where to put it, and
	 *  the comparison has to happen on one screen rather than by visiting
	 *  instances one at a time.
	 */
	workflowCompat: (rel: string, nodes: string[]) => typedError<InstanceCompat[], AppError>(__TAURI_INVOKE("workflow_compat", { rel, nodes })),
	loadSharedSettings: () => typedError<SharedSettings, AppError>(__TAURI_INVOKE("load_shared_settings")),
	saveSharedSettings: (shared: SharedSettings) => typedError<null, AppError>(__TAURI_INVOKE("save_shared_settings", { shared })),
	/**
	 *  Scans the folder and returns the categories found.
	 * 
	 *  The tree walk goes in a blocking thread: on a shared folder of hundreds of
	 *  gigabytes that is tens of thousands of metadata accesses, and holding the
	 *  main thread on them is not allowed — the interface would freeze exactly
	 *  when the user is waiting for an answer.
	 */
	scanSharedRoot: (path: string) => typedError<RootScan, AppError>(__TAURI_INVOKE("scan_shared_root", { path })),
	/**
	 *  The YAML that the current settings will produce.
	 * 
	 *  The preview is not cosmetic: the user has to see what exactly will land in
	 *  the config before it lands in their build.
	 */
	previewSharedYaml: (shared: SharedSettings) => typedError<string, AppError>(__TAURI_INVOKE("preview_shared_yaml", { shared })),
	/**  Creates the missing standard subfolders in the shared root. */
	createSharedFolders: (path: string, names: string[]) => typedError<RootScan, AppError>(__TAURI_INVOKE("create_shared_folders", { path, names })),
	/**  What is sitting in an instance's `extra_model_paths.yaml`. */
	inspectInstanceConfig: (id: string) => typedError<InstanceFileInfo, AppError>(__TAURI_INVOKE("inspect_instance_config", { id })),
	/**
	 *  Connects an instance to shared models.
	 * 
	 *  `confirm_overwrite` applies only to the "file inside the instance" mode and
	 *  only to the case where someone else's file already lies there. Without
	 *  consent the command refuses with the code `shared.foreignConfig`, and the
	 *  frontend shows the comparison screen.
	 */
	connectShared: (id: string, applyMode: ApplyMode, confirmOverwrite: boolean) => typedError<string | null, AppError>(__TAURI_INVOKE("connect_shared", { id, applyMode, confirmOverwrite })),
	/**
	 *  Disconnects an instance from shared models.
	 * 
	 *  In the "file inside the instance" mode it removes our file and puts the
	 *  saved copy of someone else's back. The models in the shared folder are
	 *  never touched.
	 */
	disconnectShared: (id: string) => typedError<null, AppError>(__TAURI_INVOKE("disconnect_shared", { id })),
	runStatuses: () => typedError<RunStatus[], AppError>(__TAURI_INVOKE("run_statuses")),
	/**
	 *  The whole accumulated log of an instance.
	 * 
	 *  Needed so that coming back to the instance screen shows the startup in
	 *  full: the events only catch what happens while the screen is open.
	 */
	runLog: (id: string) => typedError<LogLine[], AppError>(__TAURI_INVOKE("run_log", { id })),
	/**
	 *  Launches an instance.
	 * 
	 *  An unavailable shared root cannot simply be ignored: a user who kept their
	 *  models on an external drive would get a "model not found" in the middle of
	 *  their work and conclude the app is broken.
	 * 
	 *  A second build on the same graphics card means an out-of-VRAM failure once
	 *  the generation is already queued, and understanding it from ComfyUI's side
	 *  is impossible.
	 */
	startInstance: (id: string, profileId: string | null, options: StartOptions) => typedError<RunStatus, AppError>(__TAURI_INVOKE("start_instance", { id, profileId, options })),
	stopInstance: (id: string) => typedError<null, AppError>(__TAURI_INVOKE("stop_instance", { id })),
	/**
	 *  Stops an instance and brings it back up with the same profile.
	 * 
	 *  Done in Rust rather than as two calls from the frontend: `stop` returns as
	 *  soon as the port is released, while the state is moved to `Stopped` by the
	 *  process-waiting thread — and a start sent immediately after would run into
	 *  `run.alreadyRunning`. Here we simply wait for the transition to finish.
	 */
	restartInstance: (id: string) => typedError<RunStatus, AppError>(__TAURI_INVOKE("restart_instance", { id })),
	/**
	 *  Takes control of a server that restarted itself.
	 * 
	 *  After installing nodes, ComfyUI-Manager shuts the server down and brings a
	 *  new process up. Our handle is lost, the state becomes `Detached`, and from
	 *  then on the app can only watch: it does not know the new process's PID.
	 * 
	 *  We find the port's owner through the connection table and record its PID.
	 *  After that everything ordinary works again — stopping and the tab alike.
	 */
	adoptInstance: (id: string) => typedError<RunStatus, AppError>(__TAURI_INVOKE("adopt_instance", { id })),
	/**
	 *  Shows an instance's tab, creating it on the first call.
	 * 
	 *  The embedding commands have to be `async`. A synchronous Tauri command runs
	 *  on the main thread, and `add_child` from inside it queues work onto that
	 *  same thread and waits for its result — which is a deadlock without a single
	 *  error in the log.
	 */
	showComfy: (id: string, rect: Rect) => typedError<null, AppError>(__TAURI_INVOKE("show_comfy", { id, rect })),
	/**  Moves the tab along with the content area. */
	placeComfy: (id: string, rect: Rect) => typedError<null, AppError>(__TAURI_INVOKE("place_comfy", { id, rect })),
	/**  Hides every tab: leaving for another section, opening the log console. */
	hideComfy: () => typedError<null, AppError>(__TAURI_INVOKE("hide_comfy")),
	reloadComfy: (id: string) => typedError<null, AppError>(__TAURI_INVOKE("reload_comfy", { id })),
	/**
	 *  An instance's generation output folder.
	 * 
	 *  `None` means "the folder is not there yet": ComfyUI does not create it
	 *  before the first generation, and there is nothing to open. We will not
	 *  create it on the user's behalf — nothing appears inside someone else's
	 *  installation by our will.
	 */
	instanceOutputDir: (id: string, profileId: string | null) => typedError<string | null, AppError>(__TAURI_INVOKE("instance_output_dir", { id, profileId })),
	/**
	 *  Builds a report on duplicated models across every build at once.
	 * 
	 *  The command **does nothing to files** and never will: cleaning duplicates
	 *  up lives in a command of its own, on its own screen and with its own list.
	 */
	scanDuplicates: () => typedError<DuplicatesReport, AppError>(__TAURI_INVOKE("scan_duplicates")),
	cancelDuplicatesScan: () => typedError<null, AppError>(__TAURI_INVOKE("cancel_duplicates_scan")),
	/**
	 *  The tray menu labels for the current language.
	 * 
	 *  The tray menu is native, `t()` cannot reach it, and translating strings in
	 *  Rust is forbidden by the project's rules. So the text comes from the
	 *  frontend — and comes again on every change of language.
	 */
	setTrayLabels: (labels: TrayLabels) => typedError<null, AppError>(__TAURI_INVOKE("set_tray_labels", { labels })),
	/**  The instances that closing the app would take down with it. */
	busyInstances: () => typedError<string[], AppError>(__TAURI_INVOKE("busy_instances")),
	/**  Stop everything and quit. */
	stopAllAndQuit: () => typedError<null, AppError>(__TAURI_INVOKE("stop_all_and_quit")),
	/**  Collapse into the tray, leaving the servers running. */
	hideToTray: () => typedError<null, AppError>(__TAURI_INVOKE("hide_to_tray")),
	/**
	 *  Asks whether a new version is out. `None` means the latest is installed.
	 * 
	 *  Returns the error as it is and leaves the muting to the caller: the
	 *  automatic check at startup stays silent about network failures, a manual
	 *  one shows them. There is nothing in Rust to tell those apart, whereas the
	 *  frontend can see who pressed the button.
	 */
	checkUpdate: () => typedError<{
	version: string,
	/**
	 *  The one installed right now. Next to the new one so the screen does not
	 *  have to assemble the pair from two sources.
	 */
	currentVersion: string,
	/**
	 *  The release body: this version's section of `CHANGELOG.md`. Not
	 *  translated — it is release text, not an interface string.
	 */
	notes: string | null,
	/**
	 *  Epoch milliseconds, like the rest of the dates in the registry: the
	 *  frontend formats them by locale rules, not Rust.
	 */
	date: number | null,
} | null, AppError>(__TAURI_INVOKE("check_update")),
	/**
	 *  Installs the update and restarts the app.
	 * 
	 *  The "builds are running" fork works the same way as the multi-launch guard:
	 *  the first call arrives with `stop_running: false` and gets a refusal with a
	 *  code, the frontend unfolds the choice in place, and the repeat call arrives
	 *  with the answer. Silently shutting down someone's generation queue is not
	 *  allowed — the Windows installer will close us by force, and the Job Object
	 *  will take every build down with it.
	 */
	installUpdate: (stopRunning: boolean) => typedError<null, AppError>(__TAURI_INVOKE("install_update", { stopRunning })),
};

/** Events */
export const events = {
	dupProgress: makeEvent<DupProgress>("dup-progress"),
	installProgress: makeEvent<InstallProgress>("install-progress"),
	migrateProgress: makeEvent<MigrateProgress>("migrate-progress"),
	quitRequested: makeEvent<QuitRequested>("quit-requested"),
	runChanged: makeEvent<RunChanged>("run-changed"),
	runLog: makeEvent<RunLog>("run-log"),
	updateProgress: makeEvent<UpdateProgress>("update-progress"),
};

/* Types */
/**
 *  An instance's accent colour.
 * 
 *  Stored either as the name of a palette token or as an `#rrggbb` value if
 *  the user picked their own. The name is better and stays the default choice:
 *  a token has its own value in each theme, and its legibility is verified. A
 *  custom colour is the same in both themes and the user answers for it — but
 *  there is no reason to forbid them a colour of their own.
 * 
 *  A tuple struct rather than an enum: `serde` writes it transparently, so a
 *  registry written before this change reads exactly as it did, and `specta`
 *  exports it as the inner type itself.
 */
export type Accent = string;

export type AppError = {
	/**  The translation key without its prefix: `settings.saveFailed` → `errors.settings.saveFailed`. */
	code: string,
	/**
	 *  Interpolations for the message. Strings only: numbers are formatted by
	 *  the frontend according to the locale's rules anyway, not by Rust.
	 */
	params: { [key in string]: string },
};

/**  How the config is delivered to an instance. */
export type ApplyMode = 
/**
 *  The file lives with us and is passed to the instance as an argument.
 *  Nothing is written into the user's folder. The default.
 */
"flag" | 
/**
 *  The file is written to `<instance>/ComfyUI/extra_model_paths.yaml`.
 *  Needed by those who sometimes start the build from the `.bat`, past the
 *  app.
 */
"instanceFile";

export type ArchiveInfo = {
	path: string,
	/**  Имя файла. Показывается в карточке инстанса как источник. */
	label: string,
	sizeBytes: number | null,
	/**  Миллисекунды эпохи. Вместе с размером опознаёт подмену файла. */
	mtime: number | null,
	files: number,
	folders: number,
	totalUncompressed: number | null,
	/**
	 *  Единственная корневая папка архива. Её имя задаёт пользователь,
	 *  поэтому из путей она срезается — заодно минус 25 символов к длине.
	 */
	singleRoot: string | null,
	/**  Самый длинный путь внутри архива после среза корня. */
	longestEntry: number,
};

export type ArchiveRecord = {
	path: string,
	label: string,
	sizeBytes: number | null,
	mtime: number | null,
	lastUsedAt: number | null,
	/**
	 *  Файл на месте и не изменился с прошлого раза. Пересчитывается
	 *  при каждом чтении: архив могли удалить или подменить.
	 */
	available: boolean,
};

/**
 *  Everything the frontend asks for once at startup.
 * 
 *  One call rather than three: startup must not wait for three IPC round
 *  trips, or the interface has time to blink in the wrong theme.
 */
export type Bootstrap = {
	settings: UiSettings,
	sharedModels: SharedSettings,
	/**
	 *  The system language, `ru-RU` for example. The first step of language
	 *  detection; after it the frontend looks at `navigator.language` and
	 *  falls back to English.
	 */
	systemLocale: string | null,
	/**  Shown in the "About" section together with the "open folder" button. */
	appDataDir: string,
	/**
	 *  Derived data: the node snapshot cache and WebView2 data. A line of its
	 *  own because there are two folders, and both of them get deleted — the
	 *  user should not have to guess that the second one exists.
	 */
	appLocalDataDir: string,
	version: string,
};

export type CategoryStatus = 
/**  The name matched a known category or a legacy variant of one. */
"recognized" | 
/**
 *  The name is unknown. It still goes into the YAML: ComfyUI's list of
 *  categories keeps growing, and discarding the unfamiliar would mean
 *  breaking support for new versions in the name of tidiness. It is marked
 *  in the interface so that a typo like `lora` instead of `loras` catches
 *  the eye.
 */
"unknown" | 
/**  Blacklisted. Never goes into the YAML. */
"blocked";

export type CleanupOutcome = {
	removed: string[],
	freedBytes: number | null,
	failed: Failed[],
	/**  How many entries were refused because they are not duplicates. */
	refused: number,
};

/**  Where the knowledge about a build's nodes came from. */
export type CompatSource = 
/**  Asked of a running build right now. */
"live" | 
/**  From the snapshot of the last launch. */
"cached" | 
/**  The build is not running and has never been launched under us. */
"unknown";

/**  One copy of a model. */
export type Copy_ = {
	/**
	 *  The name of the build or of the shared folder. The user thinks in
	 *  places, not in identifiers.
	 */
	source: string,
	path: string,
	sizeBytes: number | null,
};

/**
 *  A custom launch profile.
 * 
 *  Only the name and the arguments are stored. The interpreter, the working
 *  folder and `env` are taken from the base profile **at launch time**: the
 *  user may have edited the `.bat` by hand, and a remembered copy would one
 *  day drift away from what is on disk.
 */
export type CustomProfile = {
	/**
	 *  `custom:<number>`. The prefix tells a custom profile apart from a
	 *  `.bat` name.
	 */
	id: string,
	name: string,
	/**
	 *  The `.bat` profile everything else is taken from. If it has
	 *  disappeared, the custom profile is shown as broken rather than launched
	 *  at random.
	 */
	baseId: string,
	args: string[],
};

/**
 *  A model occurring in more than one place.
 * 
 *  Grouped by the pair "category and name" rather than by name alone: one and
 *  the same file under `loras` and under `checkpoints` means two different
 *  roles, and merging them into one row would be offering a choice that does
 *  not exist.
 */
export type DupGroup = {
	/**  The name of the model's file or directory. Not translated. */
	name: string,
	category: string,
	copies: Copy_[],
	/**
	 *  How much is taken up beyond a single copy. Meaningless when the sizes
	 *  differ, and therefore zero in that case.
	 */
	wastedBytes: number | null,
};

export type DupProgress = {
	done: number,
	total: number,
	/**  What is being walked right now. A silent pause reads as a freeze. */
	place: string,
};

export type DuplicatesReport = {
	/**  Both the name and the size matched. Almost certainly the same thing. */
	duplicates: DupGroup[],
	/**
	 *  One name, different sizes. **These are not duplicates** — a matching
	 *  name proves nothing about the contents, and they are not counted into
	 *  the wasted total.
	 */
	nameClashes: DupGroup[],
	wastedBytes: number | null,
	/**
	 *  Folders we never reached: the build is unavailable, there is no models
	 *  folder, reading was refused. Staying silent about them is not allowed —
	 *  the report would look complete.
	 */
	skipped: string[],
	scannedPlaces: number,
	cancelled: boolean,
};

export type Failed = {
	category: string,
	name: string,
	reason: string,
};

/**
 *  A launch option that was found. In Phase 1 this is only the fact that the
 *  file exists: parsing a `.bat` into an editable profile is Phase 2's job.
 */
export type FoundProfile = {
	/**
	 *  Path relative to the instance root: `run_nvidia_gpu.bat`,
	 *  `advanced\run_nvidia_gpu_disable_api_nodes.bat`.
	 */
	id: string,
	/**  File name without the extension. Not translated: it is a file name. */
	name: string,
	/**  From the `advanced\` folder — such options are worth showing separately. */
	advanced: boolean,
};

export type InstallPhase = 
/**
 *  Проверки, открытие архива, разворот словаря LZMA2 на 768 МБ.
 *  Занимает секунды, а выглядела бы тишиной, если о ней не сказать.
 */
"preparing" | 
/**
 *  Уборка следов прерванной попытки. Отдельно от `Preparing`, потому что
 *  это единственная подготовка, способная затянуться надолго: там
 *  десятки тысяч файлов и повторы вокруг занятых антивирусом.
 */
"cleaning" | 
/**  Распаковка архива в первую цель. */
"extracting" | 
/**  Копирование готового дерева в остальные цели. */
"copying" | 
/**
 *  Регистрация в реестре: перепроверка каждой цели с запуском
 *  `python --version`. Тоже секунды, тоже не бесплатно.
 */
"registering";

export type InstallProgress = {
	phase: InstallPhase,
	/**  Номер цели, начиная с единицы, и сколько их всего. */
	target: number,
	targets: number,
	targetName: string,
	/**  Путь текущего файла внутри инстанса. Не переводится. */
	current: string,
	/**
	 *  Файлы, а не байты, — вот честная мера прогресса на этом архиве.
	 * 
	 *  Хвост сборки это `site-packages` с десятками тысяч файлов по паре
	 *  килобайт. На отметке 98% байт сделано меньше половины файлов, и полоса
	 *  стоит ровно там, где идёт самая долгая часть работы: время уходит
	 *  не на байты, а на создание файлов и проверку каждого антивирусом.
	 *  Замерено на прерванном прогоне: 27 906 файлов из 61 895 при 4.0 ГБ
	 *  из 4.1 ГБ.
	 */
	doneFiles: number,
	totalFiles: number,
	/**  Байты остаются, но уже как подпись рядом, а не как полоса. */
	doneBytes: number | null,
	totalBytes: number | null,
};

/**
 *  Where the instance came from. Filled in by the install wizard in Phase 1.5;
 *  folders added by hand have none of this.
 */
export type InstallSource = {
	archivePath: string,
	archiveLabel: string,
	/**
	 *  Epoch milliseconds. The frontend formats the date: it has to follow the
	 *  chosen language, and a string from Rust cannot do that.
	 */
	installedAt: number | null,
};

export type InstallTarget = {
	path: string,
	name: string,
	description: string,
	accent: Accent,
	preferredPort: number,
};

export type Instance = {
	id: string,
	name: string,
	description: string,
	path: string,
	accent: Accent,
	preferredPort: number,
	comfyVersion: string | null,
	pythonVersion: string | null,
	profiles: FoundProfile[],
	createdAt: number | null,
	source: InstallSource | null,
	/**
	 *  The connection to shared model storage. `#[serde(default)]` is not
	 *  decoration: a registry written before Phase 2.5 has no such field, and
	 *  without the default the parse of the whole file would fail — that is,
	 *  the user would lose their list of instances because a new setting
	 *  appeared.
	 */
	shared?: InstanceShared,
	/**
	 *  Profiles assembled by the user on top of those parsed from `.bat`.
	 * 
	 *  Ours, not an edit of someone else's: we never touch a `.bat`, and the
	 *  parse is re-read on every launch — there would be nowhere to hold an
	 *  edit to it. `#[serde(default)]` for the same reason as on `shared`: a
	 *  registry written before this phase has no such field.
	 */
	customProfiles?: CustomProfile[],
	/**
	 *  When the build was last launched, in epoch milliseconds.
	 * 
	 *  `None` means not once since the app started recording this. The
	 *  frontend formats the date: it has to follow the chosen language.
	 */
	lastStartedAt?: number | null,
	/**
	 *  Size on disk. `f64` rather than `u64`: specta forbids exporting
	 *  integers that do not fit into a JavaScript number without losing
	 *  precision. Bytes up to 9 petabytes are exactly representable in f64,
	 *  which is more than enough.
	 */
	sizeBytes: number | null,
	sizeMeasuredAt: number | null,
	/**
	 *  The folder is in place. Not really stored: recomputed on every read of
	 *  the registry. An instance whose folder has disappeared is marked
	 *  unavailable but does not vanish from the list — otherwise the user
	 *  concludes the app lost their build.
	 */
	available: boolean,
};

export type InstanceCompat = {
	instanceId: string,
	source: CompatSource,
	/**
	 *  Empty under `Unknown` — and that means "unknown", not "everything is
	 *  there". Telling them apart is the interface's job, not the reader's.
	 */
	missing: string[],
	/**
	 *  This workflow already lies in the build.
	 * 
	 *  Computed, not remembered. The interface used to know only about our own
	 *  clicks within the current session, and after a re-entry it showed "add"
	 *  for a build where the file was already present.
	 */
	present: boolean,
};

/**
 *  The metadata the user edits. A type of its own so that "rename" cannot
 *  accidentally rewrite the path or the version.
 */
export type InstanceEdit = {
	name: string,
	description: string,
	accent: Accent,
	preferredPort: number,
};

export type InstanceFileInfo = {
	path: string,
	state: InstanceFileState,
	/**
	 *  The contents of someone else's file — so the user can be shown exactly
	 *  what they are about to replace. Empty for our own and for an absent
	 *  one.
	 */
	content: string | null,
};

/**  What is sitting in an instance's `extra_model_paths.yaml`. */
export type InstanceFileState = 
/**  There is no file — we write without asking. */
"absent" | 
/**  Ours, recognised by the marker — we update silently. */
"ours" | 
/**  Someone else's. Not touched until the user decides. */
"foreign" | 
/**
 *  The file exists but will not be read. We do not touch it and we say so:
 *  overwriting what we failed to read is a sure way to destroy a working
 *  setting.
 */
"unreadable";

export type InstanceShared = {
	enabled: boolean,
	applyMode: ApplyMode,
};

/**  A build's workflow together with the verdict against the library. */
export type InstanceWorkflow = {
	path: string,
	library: LibraryMatch | null,
};

/**
 *  Where a build keeps its workflows.
 * 
 *  Separate from the list rather than a field in it: for a running build the
 *  list arrives over HTTP and does not touch the folder at all, yet showing
 *  that folder in Explorer has to work the same in both cases.
 */
export type InstanceWorkflowsDir = {
	path: string,
	/**
	 *  The folder may not exist: ComfyUI creates it lazily, on the first save.
	 *  That is not an error — there is simply nothing to show.
	 */
	available: boolean,
};

export type LaunchProfile = {
	/**  The `.bat` path relative to the instance root. Also the identifier. */
	id: string,
	/**  The file name without extension. Not translated. */
	name: string,
	advanced: boolean,
	/**  Absolute path to the interpreter. */
	pythonPath: string,
	args: string[],
	/**
	 *  The working folder is the `.bat`'s own directory. That is exactly what
	 *  gets substituted when the file is launched by double click, and what
	 *  the `..\` inside it are counted from.
	 */
	cwd: string,
	env: { [key in string]: string },
	/**
	 *  The parse failed and the launch goes through `cmd /c`. In the interface
	 *  that is a reason to warn: stopping such a process is less reliable.
	 */
	fallback: boolean,
};

export type LibraryItem = {
	/**
	 *  The path relative to the library root, with forward slashes. Also the
	 *  manifest key and what the user sees.
	 */
	path: string,
	/**  The file name without extension — for display. */
	name: string,
	meta: WorkflowMeta,
	/**  There is no file, but there is a manifest record. */
	lost: boolean,
	/**
	 *  The file did not parse as a workflow: broken JSON, or JSON with no
	 *  `nodes`. Not a library error — we show it and let it be removed.
	 */
	broken: boolean,
	/**  The graph's node classes. Empty for lost and broken ones. */
	nodes: string[],
	sizeBytes: number | null,
	modifiedAt: number | null,
};

/**
 *  What lies in the library under the same name.
 * 
 *  `None` on the outside means "the name is not in the library at all" — it
 *  can be taken without further conversation.
 */
export type LibraryMatch = 
/**  The same workflow. There is nothing to take, it is already there. */
"same" | 
/**
 *  The name is taken and the contents diverged. These are **different
 *  pieces of work**, and equating one with the other silently is not
 *  allowed.
 */
"diverged";

export type LibraryScan = {
	path: string,
	/**
	 *  The folder is absent or will not be read. Not an error: the library can
	 *  be set ahead of time, and an external drive can be unplugged.
	 */
	available: boolean,
	items: LibraryItem[],
	/**
	 *  The manifest did not parse. The files are in place and shown meanwhile
	 *  — damage to the tags has no right to carry off the workflows
	 *  themselves.
	 */
	manifestBroken: boolean,
};

/**  Workflow library settings. */
export type LibrarySettings = {
	/**
	 *  Empty means the library is not set. We do not substitute a default
	 *  into the model: "never picked" and "picked exactly this" have to stay
	 *  distinguishable, otherwise moving the shared models root would silently
	 *  drag the library along with it.
	 */
	path?: string,
};

export type LogLine = {
	/**
	 *  `stdout` or `stderr`. ComfyUI writes its startup to stderr, and telling
	 *  the streams apart is useful: stdout shows the build is already working.
	 */
	stream: string,
	/**  The contents are never translated. */
	text: string,
	/**
	 *  The line replaces the previous one instead of being appended. That is how
	 *  tqdm behaves: it prints progress with a carriage return, and without
	 *  replacement a hundred updates turn into a hundred lines.
	 */
	replacesLast: boolean,
};

export type MigrateOutcome = {
	moved: string[],
	/**  Skipped because the name was taken, with a verdict for each. */
	skipped: Skipped[],
	/**  Failed, with a reason. A failure on one does not cancel the rest. */
	failed: Failed[],
	movedBytes: number | null,
	cancelled: boolean,
};

/**
 *  Progress of the move. Counted in entries rather than bytes: within one
 *  volume a move is instantaneous, and a byte-based bar would jump about
 *  meaninglessly.
 */
export type MigrateProgress = {
	done: number,
	total: number,
	category: string,
	name: string,
};

export type ModelCategory = {
	folder: string,
	entries: ModelEntry[],
	sizeBytes: number | null,
};

export type ModelEntry = {
	/**  The entry's name inside the category. A file or a whole directory. */
	name: string,
	isDir: boolean,
	sizeBytes: number | null,
	files: number,
	/**
	 *  Whether this name is taken in the shared folder, and what it turned out
	 *  to be there.
	 */
	sameName: SameName | null,
};

export type ModelsScan = {
	path: string,
	available: boolean,
	categories: ModelCategory[],
	/**  How much will move in total and how much space it takes. */
	totalFiles: number,
	totalBytes: number | null,
};

export type Probe = {
	/**
	 *  The canonical path. Duplicate detection between instances goes by this,
	 *  not by what the user typed.
	 */
	path: string,
	comfyVersion: string | null,
	pythonVersion: string | null,
	profiles: FoundProfile[],
};

export type ProbeResult = {
	probe: Probe,
	/**
	 *  The folder is already in the registry. We do not create a second
	 *  instance for it — we show the existing one.
	 */
	existingId: string | null,
	suggestedName: string,
	suggestedPort: number,
};

export type PushOutcome = "written" | 
/**  The name is taken. A fork in the road, not an error: we ask the user. */
"conflict";

/**
 *  The "user is closing the window while servers are running" event.
 * 
 *  The route is owned by the frontend: driving navigation from Rust would
 *  create a second source of truth about which screen is where.
 */
export type QuitRequested = null;

/**
 *  The rectangle of the content area in logical pixels.
 * 
 *  Comes from `getBoundingClientRect()` of the slot on the frontend: CSS
 *  pixels and logical ones are the same thing, so display scaling needs no
 *  recalculation.
 */
export type Rect = {
	x: number | null,
	y: number | null,
	w: number | null,
	h: number | null,
};

export type RootScan = {
	path: string,
	/**
	 *  The folder is absent or unavailable. Not an error: the root can be set
	 *  ahead of time, and an external drive can be unplugged.
	 */
	available: boolean,
	categories: SharedCategory[],
	/**  Standard categories missing from the root. Offered for creation. */
	missing: string[],
	totalFiles: number,
	totalBytes: number | null,
};

/**
 *  The state-change event. It also arrives when the user did nothing: a crash
 *  and a self-restart have to be visible immediately.
 */
export type RunChanged = RunStatus;

/**
 *  The event carrying the next log line of a running instance.
 * 
 *  Named with a `Run` prefix so as not to collide with the spike's
 *  `SpikeLog`: tauri-specta derives the event name from the struct name, and
 *  identical names would have drifted apart silently.
 */
export type RunLog = {
	instanceId: string,
	line: LogLine,
};

export type RunState = "stopped" | "starting" | "running" | "stopping" | 
/**  The process exited on its own, and we did not ask it to. */
"crashed" | 
/**  The server on the port is alive, but our process no longer controls it. */
"detached";

/**  A state snapshot for the UI. */
export type RunStatus = {
	instanceId: string,
	state: RunState,
	port: number | null,
	pid: number | null,
	/**  The launch moment, in epoch milliseconds. */
	startedAt: number | null,
	/**  Seconds until readiness. Appears once the server has answered. */
	readySecs: number | null,
	/**  The exit code, if the process exited on its own. */
	exitCode: number | null,
	/**  The profile it was launched with. */
	profileId: string | null,
};

/**
 *  What an entry whose name is already taken in the shared folder turned out
 *  to be.
 */
export type SameName = 
/**  The size and the edges matched — almost certainly the same file. */
"duplicate" | 
/**
 *  A directory: the total size and the file count matched. The grounds are
 *  weaker, which is why it is named differently.
 */
"likelyDuplicate" | 
/**
 *  The sizes or the edges diverged. **Must not be deleted under any
 *  conditions:** these are different files that were unlucky with the name.
 */
"different";

export type SharedCategory = {
	/**  The subfolder's name exactly as it is on disk. */
	folder: string,
	/**
	 *  The key the folder will go into the YAML under. For legacy names it
	 *  differs from `folder`; for blocked ones it is `None`.
	 */
	key: string | null,
	status: CategoryStatus,
	files: number,
	/**
	 *  `f64` rather than `u64`: specta forbids exporting integers that do not
	 *  fit into a JavaScript number without losing precision.
	 */
	sizeBytes: number | null,
};

/**  A single shared root in the settings. */
export type SharedRoot = {
	id: string,
	path: string,
	label: string,
	enabled: boolean,
};

export type SharedSettings = {
	/**
	 *  Only one can be created in the interface so far, but the format is laid
	 *  down as an array: the "fast SSD for checkpoints, HDD for the archive"
	 *  scenario will fit without a migration — YAML can do it, one section per
	 *  root, and the order of roots sets the search priority.
	 */
	roots: SharedRoot[],
	/**
	 *  Goes into `is_default`. It only governs where ComfyUI puts newly
	 *  downloaded files: the paths are additive either way.
	 */
	makeDefaultTarget: boolean,
};

/**
 *  The measurement result. The trailing underscore is there because `Sized` is
 *  taken by the Rust prelude.
 */
export type Sized_ = {
	id: string,
	bytes: number | null,
	measuredAt: number | null,
};

export type Skipped = {
	category: string,
	name: string,
	verdict: SameName,
	sizeBytes: number | null,
};

/**
 *  The user's consents, without which the launch refuses to proceed.
 * 
 *  Both forks work the same way: the first call arrives with empty consents
 *  and gets a refusal with a code, the frontend unfolds the choice in place,
 *  and the repeat call arrives with the answer. A modal cannot be put here
 *  (the z-order discipline), and a toast has no buttons.
 */
export type StartOptions = {
	/**  Launch even if the shared models root is unavailable. */
	withoutShared?: boolean,
	/**  Launch even if another build is already running. */
	allowMultiple?: boolean,
};

/**
 *  Что не так с целью. Разделены осознанно: с предупреждением установку
 *  начать можно, с ошибкой — нет.
 */
export type TargetCheck = {
	path: string,
	errors: AppError[],
	warnings: AppError[],
};

export type ThemeChoice = "light" | "dark" | 
/**  Follow the system. */
"system";

/**
 *  Tray menu labels. They come from the frontend: the translation lives in
 *  the locales, not in Rust, and has to change along with the language.
 */
export type TrayLabels = {
	show: string,
	stopAll: string,
	quit: string,
};

/**
 *  `default` on the container is mandatory, not decoration: the settings file
 *  was written by a previous version of the app and has none of the new
 *  fields. Without it, parsing the whole struct fails on the first unfamiliar
 *  field, and the calling code reads that failure as "there are no settings" —
 *  silently resetting theme and language along with the field that was merely
 *  added.
 */
export type UiSettings = {
	theme?: ThemeChoice,
	/**
	 *  `None` until the user picks a language explicitly: detection by system
	 *  applies while it is unset. Telling "never picked" apart from "picked
	 *  English" is mandatory, otherwise a change of the Windows language stops
	 *  being taken into account.
	 */
	locale?: string | null,
	railCollapsed?: boolean,
	/**
	 *  Whether to check for updates at startup. The app's only outgoing
	 *  request, hence switchable — `NFR-355`.
	 */
	checkUpdates?: boolean,
};

/**  A newer version that was found. */
export type UpdateInfo = {
	version: string,
	/**
	 *  The one installed right now. Next to the new one so the screen does not
	 *  have to assemble the pair from two sources.
	 */
	currentVersion: string,
	/**
	 *  The release body: this version's section of `CHANGELOG.md`. Not
	 *  translated — it is release text, not an interface string.
	 */
	notes: string | null,
	/**
	 *  Epoch milliseconds, like the rest of the dates in the registry: the
	 *  frontend formats them by locale rules, not Rust.
	 */
	date: number | null,
};

/**
 *  Download progress. An event rather than a command response: a command
 *  answers once, while the install runs for tens of seconds.
 */
export type UpdateProgress = {
	downloaded: number | null,
	/**  `None` means the server sent no length. The bar is indeterminate then. */
	total: number | null,
};

/**
 *  A manifest record. Everything in it is optional: the manifest supplements a
 *  file rather than describing it.
 */
export type WorkflowMeta = {
	favorite?: boolean,
	tags?: string[],
	note?: string,
	/**  Epoch milliseconds. The frontend formats the date by locale rules. */
	addedAt?: number | null,
	/**  Which instance it was taken from, if it was taken through us. */
	sourceInstanceId?: string | null,
};

/* Tauri Specta runtime */
async function typedError<T, E>(result: Promise<T>): Promise<{ status: "ok"; data: T } | { status: "error"; error: E }> {
    try {
        return { status: "ok", data: await result };
    } catch (e) {
        if (e instanceof Error) throw e;
        return { status: "error", error: e as any };
    }
}

type EventEmit<T> = [T] extends [null] ? () => Promise<void> : (payload: T) => Promise<void>;

function makeEvent<T>(name: string, serialize?: (payload: T) => unknown, deserialize?: (payload: any) => T) {
    const mapEvent = (cb: __TAURI_EVENT.EventCallback<T>) => (event: __TAURI_EVENT.Event<any>) => cb({ ...event, payload: deserialize ? deserialize(event.payload) : event.payload });
    const mapPayload = (payload: T) => serialize ? serialize(payload) : payload;

    const base = {
        listen: (cb: __TAURI_EVENT.EventCallback<T>) => __TAURI_EVENT.listen(name, mapEvent(cb)),
        once: (cb: __TAURI_EVENT.EventCallback<T>) => __TAURI_EVENT.once(name, mapEvent(cb)),
        emit: ((payload: T) => __TAURI_EVENT.emit(name, mapPayload(payload)) as unknown) as EventEmit<T>
    };

    const fn = (target: import("@tauri-apps/api/webview").Webview | import("@tauri-apps/api/window").Window) => ({
        listen: (cb: __TAURI_EVENT.EventCallback<T>) => target.listen(name, mapEvent(cb)),
        once: (cb: __TAURI_EVENT.EventCallback<T>) => target.once(name, mapEvent(cb)),
        emit: ((payload: T) => target.emit(name, mapPayload(payload)) as unknown) as EventEmit<T>
    });

    return Object.assign(fn, base);
}

