// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE } from "@tauri-apps/api/core";
import * as __TAURI_EVENT from "@tauri-apps/api/event";

/** Commands */
export const commands = {
	/**
	 *  Настройки, прочитанные при старте: тема, язык, состояние рейла,
	 *  плюс системная локаль и пути для раздела «О приложении».
	 */
	loadBootstrap: () => typedError<Bootstrap, AppError>(__TAURI_INVOKE("load_bootstrap")),
	saveSettings: (settings: UiSettings) => typedError<null, AppError>(__TAURI_INVOKE("save_settings", { settings })),
	listInstances: () => typedError<Instance[], AppError>(__TAURI_INVOKE("list_instances")),
	/**
	 *  Проверяет выбранную папку и заодно предлагает имя, порт и цвет.
	 * 
	 *  Проверка и предложения приходят одним ответом: экран добавления
	 *  показывает их вместе, и разбивать это на три вызова незачем.
	 */
	probeFolder: (path: string) => typedError<ProbeResult, AppError>(__TAURI_INVOKE("probe_folder", { path })),
	suggestAccent: () => typedError<Accent, AppError>(__TAURI_INVOKE("suggest_accent")),
	addInstance: (path: string, edit: InstanceEdit) => typedError<Instance, AppError>(__TAURI_INVOKE("add_instance", { path, edit })),
	updateInstance: (id: string, edit: InstanceEdit) => typedError<Instance, AppError>(__TAURI_INVOKE("update_instance", { id, edit })),
	/**  Убирает инстанс из реестра. Папка на диске остаётся нетронутой. */
	removeInstance: (id: string) => typedError<null, AppError>(__TAURI_INVOKE("remove_instance", { id })),
	/**
	 *  Считает размер инстанса на диске.
	 * 
	 *  Команда `async`, поэтому выполняется не в главном потоке и интерфейс
	 *  не замирает на все минуты обхода. `None` означает, что подсчёт уже идёт.
	 */
	measureInstanceSize: (id: string) => typedError<{
	id: string,
	bytes: number | null,
	measuredAt: number | null,
} | null, AppError>(__TAURI_INVOKE("measure_instance_size", { id })),
	probeArchive: (path: string) => typedError<ArchiveInfo, AppError>(__TAURI_INVOKE("probe_archive", { path })),
	checkTargets: (info: ArchiveInfo, targets: InstallTarget[]) => typedError<TargetCheck[], AppError>(__TAURI_INVOKE("check_targets", { info, targets })),
	archiveHistory: () => typedError<ArchiveRecord[], AppError>(__TAURI_INVOKE("archive_history")),
	forgetArchive: (path: string) => typedError<null, AppError>(__TAURI_INVOKE("forget_archive", { path })),
	/**
	 *  Разворачивает архив в цели и регистрирует их.
	 * 
	 *  Команда `async`, поэтому минуты распаковки не блокируют главный поток.
	 *  Прогресс идёт событиями: возвращать его в ответе нечем, ответ один.
	 */
	runInstall: (info: ArchiveInfo, targets: InstallTarget[]) => typedError<Instance[], AppError>(__TAURI_INVOKE("run_install", { info, targets })),
	/**
	 *  Просит мастер остановиться. Проверяется между файлами, поэтому
	 *  отменённая установка не оставляет полураспакованного дерева.
	 */
	cancelInstall: () => typedError<null, AppError>(__TAURI_INVOKE("cancel_install")),
	/**  Профили запуска инстанса, разобранные из его `.bat` прямо сейчас. */
	instanceProfiles: (id: string) => typedError<LaunchProfile[], AppError>(__TAURI_INVOKE("instance_profiles", { id })),
	/**
	 *  Итоговая команда запуска — та, что реально уйдёт системе.
	 * 
	 *  Показывается в редакторе аргументов: `--port` и `--disable-auto-launch`
	 *  дописываются нами, и без предпросмотра пользователь спорил бы
	 *  с невидимым.
	 */
	previewCommand: (id: string, profileId: string) => typedError<string[], AppError>(__TAURI_INVOKE("preview_command", { id, profileId })),
	/**  Сохраняет свой профиль запуска. */
	saveCustomProfile: (id: string, profile: CustomProfile) => typedError<Instance, AppError>(__TAURI_INVOKE("save_custom_profile", { id, profile })),
	removeCustomProfile: (id: string, profileId: string) => typedError<Instance, AppError>(__TAURI_INVOKE("remove_custom_profile", { id, profileId })),
	/**  Модели этой сборки и что из них уже есть в общей папке. */
	scanInstanceModels: (id: string) => typedError<ModelsScan, AppError>(__TAURI_INVOKE("scan_instance_models", { id })),
	/**
	 *  Переносит выбранные модели в общую папку.
	 * 
	 *  Выбор приходит парами «категория и модель», как и у уборки: тумблер
	 *  на экране стоит у каждой модели, а не у категории целиком.
	 * 
	 *  Отказывает у работающей сборки: забирать файлы из-под работающего
	 *  ComfyUI нельзя — он держит их открытыми и уже разобрал пути при старте.
	 */
	migrateModels: (id: string, items: ([string, string])[]) => typedError<MigrateOutcome, AppError>(__TAURI_INVOKE("migrate_models", { id, items })),
	cancelMigrate: () => typedError<null, AppError>(__TAURI_INVOKE("cancel_migrate")),
	/**
	 *  Убирает из сборки то, что уже лежит в общей папке.
	 * 
	 *  Три условия проверяются здесь, а не только на экране: сборка
	 *  остановлена, подключена к общим моделям, и каждый элемент заново
	 *  признан дубликатом внутри `remove_duplicates`. Удаление — не то место,
	 *  где можно доверять входным данным.
	 */
	removeDuplicateModels: (id: string, items: ([string, string])[]) => typedError<CleanupOutcome, AppError>(__TAURI_INVOKE("remove_duplicate_models", { id, items })),
	/**
	 *  Куда положить свежую библиотеку, если пользователь не выбрал сам.
	 * 
	 *  Рядом с корнем общих моделей — они обычно лежат на просторном диске,
	 *  и держать воркфлоу там же логично. Жёсткой связи нет: библиотека
	 *  работает и без общих моделей, поэтому при их отсутствии просто молчим.
	 */
	suggestLibraryPath: () => typedError<string | null, AppError>(__TAURI_INVOKE("suggest_library_path")),
	loadLibrarySettings: () => typedError<LibrarySettings, AppError>(__TAURI_INVOKE("load_library_settings")),
	saveLibrarySettings: (library: LibrarySettings) => typedError<null, AppError>(__TAURI_INVOKE("save_library_settings", { library })),
	/**
	 *  Читает библиотеку целиком.
	 * 
	 *  В блокирующем потоке: обход дерева на паре сотен воркфлоу — тысячи
	 *  обращений к диску плюс разбор каждого JSON ради списка нод.
	 */
	scanLibrary: (path: string) => typedError<LibraryScan, AppError>(__TAURI_INVOKE("scan_library", { path })),
	/**
	 *  Кладёт файл с диска в библиотеку.
	 * 
	 *  Принимает и `.json`, и `.png`: картинка из папки `output` носит граф
	 *  с собой, и «перетащить картинку» — самый частый способ вернуться
	 *  к удачной генерации. В библиотеку в обоих случаях ложится `.json` —
	 *  именно он потом уедет в инстанс.
	 * 
	 *  Не воркфлоу — отказ с объяснением: библиотека обязана оставаться
	 *  библиотекой воркфлоу, а не свалкой JSON.
	 */
	addWorkflowFile: (library: string, source: string, rel: string | null, overwrite: boolean) => typedError<string, AppError>(__TAURI_INVOKE("add_workflow_file", { library, source, rel, overwrite })),
	/**
	 *  Кладёт в библиотеку граф, пришедший текстом.
	 * 
	 *  Тот же конец пути, что и у файла, только источник другой: воркфлоу
	 *  чаще присылают текстом — в чате, на форуме, — чем файлом, и сохранять
	 *  присланное в файл только ради того, чтобы тут же выбрать его в диалоге,
	 *  — лишний круг.
	 * 
	 *  Имя приходит из поля ввода, поэтому проверяется здесь, а не доверяется:
	 *  оно попадает в путь. Перезаписи нет и тут — занятое имя это отказ,
	 *  а не замена: заменить значило бы затереть одну работу другой.
	 */
	addWorkflowText: (library: string, name: string, content: string) => typedError<string, AppError>(__TAURI_INVOKE("add_workflow_text", { library, name, content })),
	/**  Правит запись манифеста: избранное, теги, заметка. */
	setWorkflowMeta: (library: string, rel: string, meta: WorkflowMeta) => typedError<null, AppError>(__TAURI_INVOKE("set_workflow_meta", { library, rel, meta })),
	/**
	 *  Убирает потерянную запись из манифеста.
	 * 
	 *  Только запись: файлов эта команда не касается вовсе — она и вызывается
	 *  лишь тогда, когда файла уже нет.
	 */
	forgetWorkflow: (library: string, rel: string) => typedError<null, AppError>(__TAURI_INVOKE("forget_workflow", { library, rel })),
	/**
	 *  Воркфлоу, лежащие в сборке.
	 * 
	 *  У запущенной спрашиваем по API, у остановленной читаем папку. Разница
	 *  не косметическая: у запущенной ответ учитывает то, что она сохранила
	 *  минуту назад, а у остановленной другого источника и нет.
	 */
	instanceWorkflows: (id: string, library: string) => typedError<InstanceWorkflow[], AppError>(__TAURI_INVOKE("instance_workflows", { id, library })),
	/**
	 *  Папка воркфлоу сборки — для кнопки «показать в проводнике».
	 * 
	 *  Существование проверяем здесь: у остановленной сборки, которая ещё
	 *  ничего не сохраняла, папки нет вовсе, и звать проводник не с чем.
	 */
	instanceWorkflowsDir: (id: string) => typedError<InstanceWorkflowsDir, AppError>(__TAURI_INVOKE("instance_workflows_dir", { id })),
	/**
	 *  Переносит воркфлоу из сборки в библиотеку: в сборке его не остаётся.
	 * 
	 *  Порядок здесь — единственная защита от потери чужой работы, и он тот же,
	 *  что у переноса моделей: пишем копию, **читаем её обратно и сверяем**,
	 *  и только потом убираем исходник. Пока копия не проверена, оригинал
	 *  должен оставаться на руках.
	 * 
	 *  Перезаписи нет вовсе. Раньше на занятое имя был вопрос «заменить?»,
	 *  и он был безобиден, пока забор был копированием: при любом ответе
	 *  воркфлоу оставался в сборке. У переноса цена ответа другая — «заменить»
	 *  затирало бы одну работу другой, не оставляя копии ни той, ни другой.
	 * 
	 *  Вместо замены — `target`: забрать под свободным именем. Занятое имя
	 *  перестало быть тупиком, но разошедшиеся версии остаются двумя разными
	 *  файлами, а не одним поверх другого.
	 * 
	 *  У запущенной сборки исходник убирает она сама, своим API: папка
	 *  воркфлоу принадлежит ей, и о правках со стороны она не знает.
	 */
	pullWorkflow: (id: string, rel: string, library: string, target: string | null) => typedError<string, AppError>(__TAURI_INVOKE("pull_workflow", { id, rel, library, target })),
	/**
	 *  Кладёт воркфлоу из библиотеки в сборку.
	 * 
	 *  У запущенной — через API с `overwrite=false`, и **409 возвращается как
	 *  развилка**, а не как ошибка: молча затирать чужой воркфлоу нельзя.
	 *  У остановленной — файлом, с той же проверкой существования.
	 */
	pushWorkflow: (id: string, library: string, rel: string, overwrite: boolean) => typedError<PushOutcome, AppError>(__TAURI_INVOKE("push_workflow", { id, library, rel, overwrite })),
	/**
	 *  Совместимость воркфлоу со всеми зарегистрированными сборками.
	 * 
	 *  Считается для всех разом: пользователь выбирает, куда класть, и сравнить
	 *  он должен на одном экране, а не обходя инстансы по одному.
	 */
	workflowCompat: (rel: string, nodes: string[]) => typedError<InstanceCompat[], AppError>(__TAURI_INVOKE("workflow_compat", { rel, nodes })),
	loadSharedSettings: () => typedError<SharedSettings, AppError>(__TAURI_INVOKE("load_shared_settings")),
	saveSharedSettings: (shared: SharedSettings) => typedError<null, AppError>(__TAURI_INVOKE("save_shared_settings", { shared })),
	/**
	 *  Сканирует папку и возвращает найденные категории.
	 * 
	 *  Обход дерева в блокирующем потоке: на общей папке в сотни гигабайт это
	 *  десятки тысяч обращений к метаданным, и держать на них главный поток
	 *  нельзя — интерфейс замрёт ровно тогда, когда пользователь ждёт ответа.
	 */
	scanSharedRoot: (path: string) => typedError<RootScan, AppError>(__TAURI_INVOKE("scan_shared_root", { path })),
	/**
	 *  YAML, который получится при текущих настройках.
	 * 
	 *  Предпросмотр не косметика: пользователь должен видеть, что именно
	 *  попадёт в конфиг, до того как это попадёт в его сборку.
	 */
	previewSharedYaml: (shared: SharedSettings) => typedError<string, AppError>(__TAURI_INVOKE("preview_shared_yaml", { shared })),
	/**  Создаёт недостающие стандартные подпапки в общем корне. */
	createSharedFolders: (path: string, names: string[]) => typedError<RootScan, AppError>(__TAURI_INVOKE("create_shared_folders", { path, names })),
	/**  Что лежит в `extra_model_paths.yaml` инстанса. */
	inspectInstanceConfig: (id: string) => typedError<InstanceFileInfo, AppError>(__TAURI_INVOKE("inspect_instance_config", { id })),
	/**
	 *  Подключает инстанс к общим моделям.
	 * 
	 *  `confirm_overwrite` относится только к режиму «файл в инстансе» и только
	 *  к случаю, когда там уже лежит чужой файл. Без согласия команда отказывает
	 *  кодом `shared.foreignConfig`, и фронт показывает экран сравнения.
	 */
	connectShared: (id: string, applyMode: ApplyMode, confirmOverwrite: boolean) => typedError<string | null, AppError>(__TAURI_INVOKE("connect_shared", { id, applyMode, confirmOverwrite })),
	/**
	 *  Отключает инстанс от общих моделей.
	 * 
	 *  В режиме «файл в инстансе» убирает наш файл и возвращает на место
	 *  сохранённую копию чужого. Модели в общей папке не трогаются никогда.
	 */
	disconnectShared: (id: string) => typedError<null, AppError>(__TAURI_INVOKE("disconnect_shared", { id })),
	runStatuses: () => typedError<RunStatus[], AppError>(__TAURI_INVOKE("run_statuses")),
	/**
	 *  Весь накопленный лог инстанса.
	 * 
	 *  Нужен, чтобы вернувшись на экран инстанса увидеть старт целиком:
	 *  события догоняют только то, что происходит при открытом экране.
	 */
	runLog: (id: string) => typedError<LogLine[], AppError>(__TAURI_INVOKE("run_log", { id })),
	/**
	 *  Запускает инстанс.
	 * 
	 *  Недоступный общий корень не может просто игнорироваться: пользователь,
	 *  державший модели на внешнем диске, получил бы «model not found» посреди
	 *  работы и решил бы, что сломалось приложение.
	 * 
	 *  Вторая сборка на той же видеокарте — это отказ по нехватке видеопамяти
	 *  уже в очереди генерации, и понять его со стороны ComfyUI невозможно.
	 */
	startInstance: (id: string, profileId: string | null, options: StartOptions) => typedError<RunStatus, AppError>(__TAURI_INVOKE("start_instance", { id, profileId, options })),
	stopInstance: (id: string) => typedError<null, AppError>(__TAURI_INVOKE("stop_instance", { id })),
	/**
	 *  Останавливает и поднимает инстанс заново тем же профилем.
	 * 
	 *  Делается в Rust, а не двумя вызовами с фронта: `stop` возвращается,
	 *  как только освободился порт, а состояние в `Stopped` переводит поток
	 *  ожидания процесса — и старт, посланный сразу следом, наткнулся бы
	 *  на `run.alreadyRunning`. Здесь мы просто дожидаемся конца перехода.
	 */
	restartInstance: (id: string) => typedError<RunStatus, AppError>(__TAURI_INVOKE("restart_instance", { id })),
	/**
	 *  Забирает под своё управление сервер, перезапустившийся сам.
	 * 
	 *  ComfyUI-Manager после установки нод гасит сервер и поднимает новый
	 *  процесс. Наш хэндл теряется, состояние становится `Detached`, и дальше
	 *  приложение умеет только смотреть: PID нового процесса ему неизвестен.
	 * 
	 *  Находим владельца порта по таблице соединений и записываем его PID.
	 *  После этого работает всё обычное — и остановка, и вкладка.
	 */
	adoptInstance: (id: string) => typedError<RunStatus, AppError>(__TAURI_INVOKE("adopt_instance", { id })),
	/**
	 *  Показывает вкладку инстанса, создавая её при первом вызове.
	 * 
	 *  Команды встраивания обязаны быть `async`. Синхронная команда Tauri
	 *  выполняется в главном потоке, а `add_child` изнутри ставит задачу
	 *  в тот же поток и ждёт её результата — получается взаимная блокировка
	 *  без единой ошибки в логе.
	 */
	showComfy: (id: string, rect: Rect) => typedError<null, AppError>(__TAURI_INVOKE("show_comfy", { id, rect })),
	/**  Переставляет вкладку вслед за областью контента. */
	placeComfy: (id: string, rect: Rect) => typedError<null, AppError>(__TAURI_INVOKE("place_comfy", { id, rect })),
	/**  Прячет все вкладки: уход в другой раздел, открытие консоли логов. */
	hideComfy: () => typedError<null, AppError>(__TAURI_INVOKE("hide_comfy")),
	reloadComfy: (id: string) => typedError<null, AppError>(__TAURI_INVOKE("reload_comfy", { id })),
	/**
	 *  Папка результатов генерации у инстанса.
	 * 
	 *  `None` означает «папки ещё нет»: до первой генерации ComfyUI её
	 *  не создаёт, и открывать нечего. Создавать её за пользователя мы
	 *  не будем — внутри чужой установки не появляется ничего по нашей воле.
	 */
	instanceOutputDir: (id: string, profileId: string | null) => typedError<string | null, AppError>(__TAURI_INVOKE("instance_output_dir", { id, profileId })),
	/**
	 *  Строит отчёт о дублирующихся моделях по всем сборкам сразу.
	 * 
	 *  Команда **ничего не делает с файлами** и делать не будет: уборка
	 *  дублей живёт отдельной командой, на своём экране и со своим перечнем.
	 */
	scanDuplicates: () => typedError<DuplicatesReport, AppError>(__TAURI_INVOKE("scan_duplicates")),
	cancelDuplicatesScan: () => typedError<null, AppError>(__TAURI_INVOKE("cancel_duplicates_scan")),
	/**
	 *  Подписи меню трея под текущий язык.
	 * 
	 *  Меню трея нативное, до `t()` ему не дотянуться, а переводить строки
	 *  в Rust правилами проекта запрещено. Поэтому текст приходит с фронта —
	 *  и приходит заново при каждой смене языка.
	 */
	setTrayLabels: (labels: TrayLabels) => typedError<null, AppError>(__TAURI_INVOKE("set_tray_labels", { labels })),
	/**  Инстансы, которые закрытие приложения унесёт с собой. */
	busyInstances: () => typedError<string[], AppError>(__TAURI_INVOKE("busy_instances")),
	/**  Остановить всё и выйти. */
	stopAllAndQuit: () => typedError<null, AppError>(__TAURI_INVOKE("stop_all_and_quit")),
	/**  Свернуть в трей, оставив серверы работать. */
	hideToTray: () => typedError<null, AppError>(__TAURI_INVOKE("hide_to_tray")),
	/**
	 *  Спрашивает, вышла ли новая версия. `None` — установлена последняя.
	 * 
	 *  Ошибку возвращает как есть, а глушит её вызывающий: автоматическая
	 *  проверка при старте молчит о сетевых сбоях, ручная — показывает.
	 *  Различить это в Rust нечем, зато на фронте видно, кто нажал кнопку.
	 */
	checkUpdate: () => typedError<{
	version: string,
	/**
	 *  Установленная сейчас. Рядом с новой, чтобы экран не собирал
	 *  пару из двух источников.
	 */
	currentVersion: string,
	/**
	 *  Тело релиза: секция `CHANGELOG.md` этой версии. Не переводится —
	 *  это текст выпуска, а не строка интерфейса.
	 */
	notes: string | null,
	/**
	 *  Миллисекунды эпохи, как и остальные даты в реестре: форматирует их
	 *  фронт по правилам локали, а не Rust.
	 */
	date: number | null,
} | null, AppError>(__TAURI_INVOKE("check_update")),
	/**
	 *  Ставит обновление и перезапускает приложение.
	 * 
	 *  Развилка «работают сборки» устроена так же, как гард мульти-запуска:
	 *  первый вызов приходит с `stop_running: false` и получает отказ с кодом,
	 *  фронт раскрывает выбор на месте, повторный вызов приходит уже с ответом.
	 *  Молча гасить чужую очередь генерации нельзя — инсталлятор Windows
	 *  закроет нас принудительно, а Job Object унесёт с собой все сборки.
	 */
	installUpdate: (stopRunning: boolean) => typedError<null, AppError>(__TAURI_INVOKE("install_update", { stopRunning })),
};

/** Events */
export const events = {
	dupProgress: makeEvent<DupProgress>("dup-progress"),
	installProgress: makeEvent<InstallProgress>("install-progress"),
	migrateProgress: makeEvent<MigrateProgress>("migrate-progress"),
	quitRequested: makeEvent<QuitRequested>("quit-requested"),
	runChanged: makeEvent<RunChanged>("run-changed"),
	runLog: makeEvent<RunLog>("run-log"),
	updateProgress: makeEvent<UpdateProgress>("update-progress"),
};

/* Types */
/**
 *  Акцентный цвет инстанса.
 * 
 *  Хранится либо именем токена палитры, либо значением `#rrggbb`, если
 *  пользователь выбрал свой. Имя лучше и остаётся выбором по умолчанию:
 *  у токена своё значение в каждой теме, и читаемость проверена. Свой
 *  цвет одинаков в обеих темах, и отвечает за него уже пользователь —
 *  но запрещать ему собственный цвет не за что.
 * 
 *  Кортежная структура, а не перечисление: `serde` пишет её прозрачно,
 *  то есть реестр, записанный до этой правки, читается как был,
 *  а `specta` экспортирует её самим внутренним типом.
 */
export type Accent = string;

export type AppError = {
	/**  The translation key without its prefix: `settings.saveFailed` → `errors.settings.saveFailed`. */
	code: string,
	/**
	 *  Interpolations for the message. Strings only: numbers are formatted by
	 *  the frontend according to the locale's rules anyway, not by Rust.
	 */
	params: { [key in string]: string },
};

/**  Способ доставки конфига инстансу. */
export type ApplyMode = 
/**
 *  Файл живёт у нас, инстансу передаётся аргументом. В папку
 *  пользователя не пишется ничего. По умолчанию.
 */
"flag" | 
/**
 *  Файл пишется в `<instance>/ComfyUI/extra_model_paths.yaml`. Нужен тем,
 *  кто иногда стартует сборку через `.bat` мимо приложения.
 */
"instanceFile";

export type ArchiveInfo = {
	path: string,
	/**  Имя файла. Показывается в карточке инстанса как источник. */
	label: string,
	sizeBytes: number | null,
	/**  Миллисекунды эпохи. Вместе с размером опознаёт подмену файла. */
	mtime: number | null,
	files: number,
	folders: number,
	totalUncompressed: number | null,
	/**
	 *  Единственная корневая папка архива. Её имя задаёт пользователь,
	 *  поэтому из путей она срезается — заодно минус 25 символов к длине.
	 */
	singleRoot: string | null,
	/**  Самый длинный путь внутри архива после среза корня. */
	longestEntry: number,
};

export type ArchiveRecord = {
	path: string,
	label: string,
	sizeBytes: number | null,
	mtime: number | null,
	lastUsedAt: number | null,
	/**
	 *  Файл на месте и не изменился с прошлого раза. Пересчитывается
	 *  при каждом чтении: архив могли удалить или подменить.
	 */
	available: boolean,
};

/**
 *  Всё, что фронт спрашивает один раз при запуске.
 * 
 *  Одним вызовом, а не тремя: старт не должен ждать три круга IPC,
 *  иначе интерфейс успевает моргнуть чужой темой.
 */
export type Bootstrap = {
	settings: UiSettings,
	sharedModels: SharedSettings,
	/**
	 *  Язык системы, например `ru-RU`. Первый шаг определения языка;
	 *  дальше фронт смотрит на `navigator.language` и падает в английский.
	 */
	systemLocale: string | null,
	/**  Показывается в разделе «О приложении» вместе с кнопкой «открыть папку». */
	appDataDir: string,
	/**
	 *  Производное: кэш снимков нод и данные WebView2. Отдельной строкой,
	 *  потому что папки две, и удаляются они тоже обе — пользователь
	 *  не должен догадываться о существовании второй.
	 */
	appLocalDataDir: string,
	version: string,
};

export type CategoryStatus = 
/**  Имя совпало с известной категорией или с её устаревшим вариантом. */
"recognized" | 
/**
 *  Имя неизвестно. В YAML всё равно попадает: список категорий ComfyUI
 *  растёт, и отбрасывать незнакомое значило бы ломать поддержку новых
 *  версий ради аккуратности. В интерфейсе помечается, чтобы опечатка
 *  вроде `lora` вместо `loras` бросалась в глаза.
 */
"unknown" | 
/**  Чёрный список. В YAML не попадает никогда. */
"blocked";

export type CleanupOutcome = {
	removed: string[],
	freedBytes: number | null,
	failed: Failed[],
	/**  Сколько элементов отклонено, потому что дубликатами не являются. */
	refused: number,
};

/**  Откуда взяты сведения о нодах сборки. */
export type CompatSource = 
/**  Спросили у работающей сборки прямо сейчас. */
"live" | 
/**  По снимку с последнего запуска. */
"cached" | 
/**  Сборка не запущена и ни разу не запускалась при нас. */
"unknown";

/**  Одна копия модели. */
export type Copy_ = {
	/**
	 *  Имя сборки либо общей папки. Пользователь думает местами,
	 *  а не идентификаторами.
	 */
	source: string,
	path: string,
	sizeBytes: number | null,
};

/**
 *  Свой профиль запуска.
 * 
 *  Хранятся только имя и аргументы. Интерпретатор, рабочая папка и `env`
 *  берутся у базового профиля **в момент запуска**: пользователь мог
 *  поправить `.bat` руками, и запомненная копия однажды разошлась бы
 *  с тем, что лежит на диске.
 */
export type CustomProfile = {
	/**  `custom:<число>`. Префикс отличает свой профиль от имени `.bat`. */
	id: string,
	name: string,
	/**
	 *  Профиль из `.bat`, у которого берётся всё остальное. Если он исчез —
	 *  свой профиль показывается сломанным, а не запускается наугад.
	 */
	baseId: string,
	args: string[],
};

/**
 *  Модель, встречающаяся больше чем в одном месте.
 * 
 *  Группируем по паре «категория и имя», а не по одному имени: один
 *  и тот же файл под `loras` и под `checkpoints` — это разные роли,
 *  и сводить их в одну строку значило бы предлагать выбор, которого нет.
 */
export type DupGroup = {
	/**  Имя файла или каталога модели. Не переводится. */
	name: string,
	category: string,
	copies: Copy_[],
	/**
	 *  Сколько занято сверх одной копии. У разных размеров смысла не имеет
	 *  и потому равно нулю.
	 */
	wastedBytes: number | null,
};

export type DupProgress = {
	done: number,
	total: number,
	/**  Что обходим прямо сейчас. Молчаливая пауза читается как зависание. */
	place: string,
};

export type DuplicatesReport = {
	/**  Совпали и имя, и размер. Почти наверняка одно и то же. */
	duplicates: DupGroup[],
	/**
	 *  Одно имя, разные размеры. **Это не дубликаты** — совпадение имени
	 *  содержимого не доказывает, и в сумму потерь они не входят.
	 */
	nameClashes: DupGroup[],
	wastedBytes: number | null,
	/**
	 *  Папки, до которых не добрались: сборка недоступна, папки моделей
	 *  нет, читать не дали. Молчать о них нельзя — отчёт выглядел бы полным.
	 */
	skipped: string[],
	scannedPlaces: number,
	cancelled: boolean,
};

export type Failed = {
	category: string,
	name: string,
	reason: string,
};

/**
 *  A launch option that was found. In Phase 1 this is only the fact that the
 *  file exists: parsing a `.bat` into an editable profile is Phase 2's job.
 */
export type FoundProfile = {
	/**
	 *  Path relative to the instance root: `run_nvidia_gpu.bat`,
	 *  `advanced\run_nvidia_gpu_disable_api_nodes.bat`.
	 */
	id: string,
	/**  File name without the extension. Not translated: it is a file name. */
	name: string,
	/**  From the `advanced\` folder — such options are worth showing separately. */
	advanced: boolean,
};

export type InstallPhase = 
/**
 *  Проверки, открытие архива, разворот словаря LZMA2 на 768 МБ.
 *  Занимает секунды, а выглядела бы тишиной, если о ней не сказать.
 */
"preparing" | 
/**
 *  Уборка следов прерванной попытки. Отдельно от `Preparing`, потому что
 *  это единственная подготовка, способная затянуться надолго: там
 *  десятки тысяч файлов и повторы вокруг занятых антивирусом.
 */
"cleaning" | 
/**  Распаковка архива в первую цель. */
"extracting" | 
/**  Копирование готового дерева в остальные цели. */
"copying" | 
/**
 *  Регистрация в реестре: перепроверка каждой цели с запуском
 *  `python --version`. Тоже секунды, тоже не бесплатно.
 */
"registering";

export type InstallProgress = {
	phase: InstallPhase,
	/**  Номер цели, начиная с единицы, и сколько их всего. */
	target: number,
	targets: number,
	targetName: string,
	/**  Путь текущего файла внутри инстанса. Не переводится. */
	current: string,
	/**
	 *  Файлы, а не байты, — вот честная мера прогресса на этом архиве.
	 * 
	 *  Хвост сборки это `site-packages` с десятками тысяч файлов по паре
	 *  килобайт. На отметке 98% байт сделано меньше половины файлов, и полоса
	 *  стоит ровно там, где идёт самая долгая часть работы: время уходит
	 *  не на байты, а на создание файлов и проверку каждого антивирусом.
	 *  Замерено на прерванном прогоне: 27 906 файлов из 61 895 при 4.0 ГБ
	 *  из 4.1 ГБ.
	 */
	doneFiles: number,
	totalFiles: number,
	/**  Байты остаются, но уже как подпись рядом, а не как полоса. */
	doneBytes: number | null,
	totalBytes: number | null,
};

/**
 *  Откуда взялся инстанс. Заполняет мастер установки в Фазе 1.5;
 *  у добавленных вручную папок этого нет.
 */
export type InstallSource = {
	archivePath: string,
	archiveLabel: string,
	/**
	 *  Миллисекунды эпохи. Дату форматирует фронт: она обязана следовать
	 *  выбранному языку, а строка из Rust этого не умеет.
	 */
	installedAt: number | null,
};

export type InstallTarget = {
	path: string,
	name: string,
	description: string,
	accent: Accent,
	preferredPort: number,
};

export type Instance = {
	id: string,
	name: string,
	description: string,
	path: string,
	accent: Accent,
	preferredPort: number,
	comfyVersion: string | null,
	pythonVersion: string | null,
	profiles: FoundProfile[],
	createdAt: number | null,
	source: InstallSource | null,
	/**
	 *  Подключение к общему хранилищу моделей. `#[serde(default)]` не
	 *  украшение: реестр, записанный до Фазы 2.5, поля не содержит, и без
	 *  умолчания разбор всего файла упал бы — то есть пользователь потерял
	 *  бы список инстансов из-за появления новой настройки.
	 */
	shared?: InstanceShared,
	/**
	 *  Профили, собранные пользователем поверх разобранных из `.bat`.
	 * 
	 *  Свои, а не правка чужих: `.bat` мы не трогаем никогда, а разбор
	 *  перечитывается при каждом запуске — правку в него было бы негде
	 *  удержать. `#[serde(default)]` по той же причине, что у `shared`:
	 *  реестр, записанный до этой фазы, поля не содержит.
	 */
	customProfiles?: CustomProfile[],
	/**
	 *  Когда сборку запускали в последний раз, в миллисекундах эпохи.
	 * 
	 *  `None` — ни разу с тех пор, как приложение это записывает. Дату
	 *  форматирует фронт: она обязана следовать выбранному языку.
	 */
	lastStartedAt?: number | null,
	/**
	 *  Размер на диске. `f64`, а не `u64`: specta запрещает экспорт целых,
	 *  не помещающихся в число JavaScript без потери точности. Байты
	 *  до 9 петабайт в f64 представимы точно, этого хватит с запасом.
	 */
	sizeBytes: number | null,
	sizeMeasuredAt: number | null,
	/**
	 *  Папка на месте. Не хранится по-настоящему: пересчитывается при
	 *  каждом чтении реестра. Инстанс с исчезнувшей папкой помечается
	 *  недоступным, но из списка не пропадает — иначе пользователь решит,
	 *  что приложение потеряло его сборку.
	 */
	available: boolean,
};

export type InstanceCompat = {
	instanceId: string,
	source: CompatSource,
	/**
	 *  Пусто при `Unknown` — и это не «всё на месте», а «неизвестно».
	 *  Различать обязан интерфейс, а не читатель.
	 */
	missing: string[],
	/**
	 *  Этот воркфлоу уже лежит в сборке.
	 * 
	 *  Считается, а не запоминается. Прежде интерфейс знал только о наших
	 *  собственных нажатиях в текущем сеансе и после перезахода показывал
	 *  «добавить» у сборки, где файл уже был.
	 */
	present: boolean,
};

/**
 *  Метаданные, которые правит пользователь. Отдельным типом, чтобы
 *  «переименовать» не могло случайно переписать путь или версию.
 */
export type InstanceEdit = {
	name: string,
	description: string,
	accent: Accent,
	preferredPort: number,
};

export type InstanceFileInfo = {
	path: string,
	state: InstanceFileState,
	/**
	 *  Содержимое чужого файла — чтобы показать пользователю, что именно
	 *  он собирается заменить. У своего и отсутствующего пусто.
	 */
	content: string | null,
};

/**  Что лежит в `extra_model_paths.yaml` инстанса. */
export type InstanceFileState = 
/**  Файла нет — пишем без вопросов. */
"absent" | 
/**  Наш, узнан по маркеру, — обновляем молча. */
"ours" | 
/**  Чужой. Не трогаем, пока пользователь не решит. */
"foreign" | 
/**
 *  Файл есть, но не читается. Не трогаем и говорим об этом:
 *  перезаписать то, что не смогли прочитать, — верный способ
 *  уничтожить работающую настройку.
 */
"unreadable";

export type InstanceShared = {
	enabled: boolean,
	applyMode: ApplyMode,
};

/**  Воркфлоу сборки вместе с вердиктом по библиотеке. */
export type InstanceWorkflow = {
	path: string,
	library: LibraryMatch | null,
};

/**
 *  Где у сборки лежат её воркфлоу.
 * 
 *  Отдельно от списка, а не полем в нём: у запущенной сборки список
 *  приходит по HTTP и папки не касается вовсе, а показать её в проводнике
 *  нужно одинаково в обоих случаях.
 */
export type InstanceWorkflowsDir = {
	path: string,
	/**
	 *  Папки может не быть: ComfyUI заводит её лениво, при первом
	 *  сохранении. Это не ошибка — просто показывать нечего.
	 */
	available: boolean,
};

export type LaunchProfile = {
	/**  Путь `.bat` относительно корня инстанса. Он же идентификатор. */
	id: string,
	/**  Имя файла без расширения. Не переводится. */
	name: string,
	advanced: boolean,
	/**  Абсолютный путь к интерпретатору. */
	pythonPath: string,
	args: string[],
	/**
	 *  Рабочая папка — директория самого `.bat`. Именно она подставляется,
	 *  когда файл запускают двойным кликом, и от неё считаются `..\` внутри.
	 */
	cwd: string,
	env: { [key in string]: string },
	/**
	 *  Разобрать не удалось, запуск пойдёт через `cmd /c`. В интерфейсе
	 *  это повод предупредить: остановка такого процесса менее надёжна.
	 */
	fallback: boolean,
};

export type LibraryItem = {
	/**
	 *  Путь относительно корня библиотеки, прямыми слэшами. Он же ключ
	 *  манифеста и то, что видит пользователь.
	 */
	path: string,
	/**  Имя файла без расширения — для показа. */
	name: string,
	meta: WorkflowMeta,
	/**  Файла нет, а запись в манифесте есть. */
	lost: boolean,
	/**
	 *  Файл не разобрался как воркфлоу: битый JSON или JSON без `nodes`.
	 *  Не ошибка библиотеки — показываем и даём убрать.
	 */
	broken: boolean,
	/**  Классы нод из графа. У потерянных и битых пусто. */
	nodes: string[],
	sizeBytes: number | null,
	modifiedAt: number | null,
};

/**
 *  Что лежит в библиотеке под тем же именем.
 * 
 *  `None` снаружи означает «имени в библиотеке нет вовсе» — забирать можно
 *  без разговоров.
 */
export type LibraryMatch = 
/**  Тот же воркфлоу. Забирать нечего, он уже там. */
"same" | 
/**
 *  Имя занято, а содержимое разошлось. Это **разные работы**,
 *  и молча приравнивать их одну к другой нельзя.
 */
"diverged";

export type LibraryScan = {
	path: string,
	/**
	 *  Папки нет или она не читается. Не ошибка: библиотеку можно задать
	 *  заранее, а внешний диск — отключить.
	 */
	available: boolean,
	items: LibraryItem[],
	/**
	 *  Манифест не разобрался. Файлы при этом на месте и показаны —
	 *  повреждение тегов не имеет права уносить сами воркфлоу.
	 */
	manifestBroken: boolean,
};

/**  Настройки библиотеки воркфлоу. */
export type LibrarySettings = {
	/**
	 *  Пусто — библиотека не задана. Дефолт не подставляем в модель:
	 *  «не выбирал» и «выбрал вот это» обязаны различаться, иначе смена
	 *  корня общих моделей молча уводила бы библиотеку следом.
	 */
	path?: string,
};

export type LogLine = {
	/**
	 *  `stdout` or `stderr`. ComfyUI writes its startup to stderr, and telling
	 *  the streams apart is useful: stdout shows the build is already working.
	 */
	stream: string,
	/**  The contents are never translated. */
	text: string,
	/**
	 *  The line replaces the previous one instead of being appended. That is how
	 *  tqdm behaves: it prints progress with a carriage return, and without
	 *  replacement a hundred updates turn into a hundred lines.
	 */
	replacesLast: boolean,
};

export type MigrateOutcome = {
	moved: string[],
	/**  Пропущенные из-за занятого имени, с вердиктом по каждому. */
	skipped: Skipped[],
	/**  Не удалось, с причиной. Сбой на одном не отменяет остальные. */
	failed: Failed[],
	movedBytes: number | null,
	cancelled: boolean,
};

/**
 *  Ход переноса. Считается по элементам, а не по байтам: на одном томе
 *  перенос мгновенен, и полоса по байтам прыгала бы бессмысленно.
 */
export type MigrateProgress = {
	done: number,
	total: number,
	category: string,
	name: string,
};

export type ModelCategory = {
	folder: string,
	entries: ModelEntry[],
	sizeBytes: number | null,
};

export type ModelEntry = {
	/**  Имя элемента внутри категории. Файл или каталог целиком. */
	name: string,
	isDir: boolean,
	sizeBytes: number | null,
	files: number,
	/**  Занято ли это имя в общей папке и чем оно там оказалось. */
	sameName: SameName | null,
};

export type ModelsScan = {
	path: string,
	available: boolean,
	categories: ModelCategory[],
	/**  Сколько всего перенесётся и сколько это займёт. */
	totalFiles: number,
	totalBytes: number | null,
};

export type Probe = {
	/**
	 *  The canonical path. Duplicate detection between instances goes by this,
	 *  not by what the user typed.
	 */
	path: string,
	comfyVersion: string | null,
	pythonVersion: string | null,
	profiles: FoundProfile[],
};

export type ProbeResult = {
	probe: Probe,
	/**
	 *  Папка уже в реестре. Второй инстанс на неё не заводим — показываем
	 *  существующий.
	 */
	existingId: string | null,
	suggestedName: string,
	suggestedPort: number,
};

export type PushOutcome = "written" | 
/**  Имя занято. Развилка, а не ошибка: спрашиваем пользователя. */
"conflict";

/**
 *  Событие «пользователь закрывает окно, а серверы работают».
 * 
 *  Роутом владеет фронт: вести навигацию из Rust значило бы завести
 *  второй источник правды о том, где какой экран.
 */
export type QuitRequested = null;

/**
 *  Прямоугольник области контента в логических пикселях.
 * 
 *  Приходит из `getBoundingClientRect()` слота на фронте: CSS-пиксели
 *  и логические — одно и то же, поэтому масштабирование экрана
 *  пересчитывать не надо.
 */
export type Rect = {
	x: number | null,
	y: number | null,
	w: number | null,
	h: number | null,
};

export type RootScan = {
	path: string,
	/**
	 *  Папки нет или она недоступна. Не ошибка: корень можно задать заранее,
	 *  а внешний диск — отключить.
	 */
	available: boolean,
	categories: SharedCategory[],
	/**  Стандартные категории, которых в корне нет. Предлагаются к созданию. */
	missing: string[],
	totalFiles: number,
	totalBytes: number | null,
};

/**
 *  Событие смены состояния. Приходит и тогда, когда пользователь ничего
 *  не делал: падение и самоперезапуск обязаны быть видны сразу.
 */
export type RunChanged = RunStatus;

/**
 *  Событие с очередной строкой лога запущенного инстанса.
 * 
 *  Имя с префиксом `Run`, чтобы не столкнуться с `SpikeLog` спайка:
 *  tauri-specta выводит имя события из имени структуры, и одинаковые
 *  имена разъехались бы молча.
 */
export type RunLog = {
	instanceId: string,
	line: LogLine,
};

export type RunState = "stopped" | "starting" | "running" | "stopping" | 
/**  The process exited on its own, and we did not ask it to. */
"crashed" | 
/**  The server on the port is alive, but our process no longer controls it. */
"detached";

/**  A state snapshot for the UI. */
export type RunStatus = {
	instanceId: string,
	state: RunState,
	port: number | null,
	pid: number | null,
	/**  The launch moment, in epoch milliseconds. */
	startedAt: number | null,
	/**  Seconds until readiness. Appears once the server has answered. */
	readySecs: number | null,
	/**  The exit code, if the process exited on its own. */
	exitCode: number | null,
	/**  The profile it was launched with. */
	profileId: string | null,
};

/**  Чем оказался элемент, чьё имя уже занято в общей папке. */
export type SameName = 
/**  Совпали размер и края — почти наверняка тот же файл. */
"duplicate" | 
/**
 *  Каталог: совпали суммарный объём и число файлов. Основание слабее,
 *  поэтому и называется иначе.
 */
"likelyDuplicate" | 
/**
 *  Размеры или края разошлись. **Удалять нельзя ни при каких условиях:**
 *  это разные файлы, которым не повезло с именем.
 */
"different";

export type SharedCategory = {
	/**  Имя подпапки как оно есть на диске. */
	folder: string,
	/**
	 *  Ключ, под которым папка уедет в YAML. У устаревших имён отличается
	 *  от `folder`; у заблокированных — `None`.
	 */
	key: string | null,
	status: CategoryStatus,
	files: number,
	/**
	 *  `f64`, а не `u64`: specta запрещает экспорт целых, не помещающихся
	 *  в число JavaScript без потери точности.
	 */
	sizeBytes: number | null,
};

/**  Один общий корень в настройках. */
export type SharedRoot = {
	id: string,
	path: string,
	label: string,
	enabled: boolean,
};

export type SharedSettings = {
	/**
	 *  В интерфейсе пока заводится один, но формат заложен массивом:
	 *  сценарий «быстрый SSD под checkpoints, HDD под архив» ляжет
	 *  без миграции — YAML это умеет, одна секция на корень, а порядок
	 *  корней определяет приоритет поиска.
	 */
	roots: SharedRoot[],
	/**
	 *  Уезжает в `is_default`. Управляет только тем, куда ComfyUI кладёт
	 *  вновь скачанное: пути в любом случае аддитивны.
	 */
	makeDefaultTarget: boolean,
};

/**  Результат подсчёта. Имя с подчёркиванием — `Sized` занято в прелюдии Rust. */
export type Sized_ = {
	id: string,
	bytes: number | null,
	measuredAt: number | null,
};

export type Skipped = {
	category: string,
	name: string,
	verdict: SameName,
	sizeBytes: number | null,
};

/**
 *  Согласия пользователя, без которых запуск отказывается идти.
 * 
 *  Обе развилки устроены одинаково: первый вызов приходит с пустыми
 *  согласиями и получает отказ с кодом, фронт раскрывает выбор на месте,
 *  повторный вызов приходит уже с ответом. Модалку сюда положить нельзя
 *  (дисциплина z-order), а у тоста не бывает кнопок.
 */
export type StartOptions = {
	/**  Запускаться, даже если общий корень моделей недоступен. */
	withoutShared?: boolean,
	/**  Запускаться, даже если другая сборка уже работает. */
	allowMultiple?: boolean,
};

/**
 *  Что не так с целью. Разделены осознанно: с предупреждением установку
 *  начать можно, с ошибкой — нет.
 */
export type TargetCheck = {
	path: string,
	errors: AppError[],
	warnings: AppError[],
};

export type ThemeChoice = "light" | "dark" | 
/**  Следовать системе. */
"system";

/**
 *  Подписи меню трея. Приходят с фронта: перевод живёт в локалях, а не
 *  в Rust, и меняться обязан вместе с языком.
 */
export type TrayLabels = {
	show: string,
	stopAll: string,
	quit: string,
};

/**
 *  `default` на контейнере обязателен, а не украшение: файл настроек
 *  пишется прошлой версией приложения и новых полей не содержит. Без него
 *  разбор всей структуры проваливается на первом же незнакомом поле,
 *  а вызывающий код трактует провал как «настроек нет» — и молча сбрасывает
 *  тему с языком заодно с тем полем, которое всего лишь добавили.
 */
export type UiSettings = {
	theme?: ThemeChoice,
	/**
	 *  `None`, пока пользователь не выбрал язык явно: тогда работает
	 *  определение по системе. Отличать «не выбирал» от «выбрал английский»
	 *  обязательно, иначе смена языка Windows перестанет учитываться.
	 */
	locale?: string | null,
	railCollapsed?: boolean,
	/**
	 *  Проверять ли обновления при запуске. Единственное исходящее
	 *  обращение приложения, поэтому выключаемое — `NFR-355`.
	 */
	checkUpdates?: boolean,
};

/**  Найденная новая версия. */
export type UpdateInfo = {
	version: string,
	/**
	 *  Установленная сейчас. Рядом с новой, чтобы экран не собирал
	 *  пару из двух источников.
	 */
	currentVersion: string,
	/**
	 *  Тело релиза: секция `CHANGELOG.md` этой версии. Не переводится —
	 *  это текст выпуска, а не строка интерфейса.
	 */
	notes: string | null,
	/**
	 *  Миллисекунды эпохи, как и остальные даты в реестре: форматирует их
	 *  фронт по правилам локали, а не Rust.
	 */
	date: number | null,
};

/**
 *  Ход загрузки. Событием, а не ответом команды: ответ у команды один,
 *  а установка идёт десятки секунд.
 */
export type UpdateProgress = {
	downloaded: number | null,
	/**  `None` — сервер не прислал длину. Тогда полоса индетерминантная. */
	total: number | null,
};

/**
 *  Запись манифеста. Всё в ней необязательное: манифест дополняет файл,
 *  а не описывает его.
 */
export type WorkflowMeta = {
	favorite?: boolean,
	tags?: string[],
	note?: string,
	/**  Миллисекунды эпохи. Дату форматирует фронт по правилам локали. */
	addedAt?: number | null,
	/**  Из какого инстанса забран, если забирали через нас. */
	sourceInstanceId?: string | null,
};

/* Tauri Specta runtime */
async function typedError<T, E>(result: Promise<T>): Promise<{ status: "ok"; data: T } | { status: "error"; error: E }> {
    try {
        return { status: "ok", data: await result };
    } catch (e) {
        if (e instanceof Error) throw e;
        return { status: "error", error: e as any };
    }
}

type EventEmit<T> = [T] extends [null] ? () => Promise<void> : (payload: T) => Promise<void>;

function makeEvent<T>(name: string, serialize?: (payload: T) => unknown, deserialize?: (payload: any) => T) {
    const mapEvent = (cb: __TAURI_EVENT.EventCallback<T>) => (event: __TAURI_EVENT.Event<any>) => cb({ ...event, payload: deserialize ? deserialize(event.payload) : event.payload });
    const mapPayload = (payload: T) => serialize ? serialize(payload) : payload;

    const base = {
        listen: (cb: __TAURI_EVENT.EventCallback<T>) => __TAURI_EVENT.listen(name, mapEvent(cb)),
        once: (cb: __TAURI_EVENT.EventCallback<T>) => __TAURI_EVENT.once(name, mapEvent(cb)),
        emit: ((payload: T) => __TAURI_EVENT.emit(name, mapPayload(payload)) as unknown) as EventEmit<T>
    };

    const fn = (target: import("@tauri-apps/api/webview").Webview | import("@tauri-apps/api/window").Window) => ({
        listen: (cb: __TAURI_EVENT.EventCallback<T>) => target.listen(name, mapEvent(cb)),
        once: (cb: __TAURI_EVENT.EventCallback<T>) => target.once(name, mapEvent(cb)),
        emit: ((payload: T) => target.emit(name, mapPayload(payload)) as unknown) as EventEmit<T>
    });

    return Object.assign(fn, base);
}

